# Practice Test 1a

#### Karolina Binkevičiūtė

### Q1

1. Create a dataframe with 1020 rows and twenty columns. Values can be random.
2. Change the names of the columns into Lithuanian city names.
3. Calculate the means of top three biggest cities in your dataset.
4. Remove the first city column.
5. For each column calculate it's mean and change each column's values to the mean.

In [1]:
import numpy as np
import pandas as pd

In [43]:
data = pd.DataFrame(np.arange(20400).reshape((1020, 20)))
data

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
1,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39
2,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59
3,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79
4,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1015,20300,20301,20302,20303,20304,20305,20306,20307,20308,20309,20310,20311,20312,20313,20314,20315,20316,20317,20318,20319
1016,20320,20321,20322,20323,20324,20325,20326,20327,20328,20329,20330,20331,20332,20333,20334,20335,20336,20337,20338,20339
1017,20340,20341,20342,20343,20344,20345,20346,20347,20348,20349,20350,20351,20352,20353,20354,20355,20356,20357,20358,20359
1018,20360,20361,20362,20363,20364,20365,20366,20367,20368,20369,20370,20371,20372,20373,20374,20375,20376,20377,20378,20379
1019,20380,20381,20382,20383,20384,20385,20386,20387,20388,20389,20390,20391,20392,20393,20394,20395,20396,20397,20398,20399

In [44]:
data = pd.DataFrame(np.arange(20400).reshape((1020, 20)),
                   columns=['Birštonas', 'Kaunas', 'Vilnius', 'Klaipėda', 'Biržai', 'Druskininkai', 'Prienai', 'Šiauliai', 'Alytus', 'Jonava', 'Kėdainiai', 'Kretinga', 'Kupiškis', 'Palanga', 'Šventoji', 'Marijampolė', 'Pakruojis', 'Panevėžys','Plungė' ,'Rokiškis'])
data

,Birštonas,Kaunas,Vilnius,Klaipėda,Biržai,Druskininkai,Prienai,Šiauliai,Alytus,Jonava,Kėdainiai,Kretinga,Kupiškis,Palanga,Šventoji,Marijampolė,Pakruojis,Panevėžys,Plungė,Rokiškis
0,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
1,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39
2,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59
3,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79
4,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1015,20300,20301,20302,20303,20304,20305,20306,20307,20308,20309,20310,20311,20312,20313,20314,20315,20316,20317,20318,20319
1016,20320,20321,20322,20323,20324,20325,20326,20327,20328,20329,20330,20331,20332,20333,20334,20335,20336,20337,20338,20339
1017,20340,20341,20342,20343,20344,20345,20346,20347,20348,20349,20350,20351,20352,20353,20354,20355,20356,20357,20358,20359
1018,20360,20361,20362,20363,20364,20365,20366,20367,20368,20369,20370,20371,20372,20373,20374,20375,20376,20377,20378,20379
1019,20380,20381,20382,20383,20384,20385,20386,20387,20388,20389,20390,20391,20392,20393,20394,20395,20396,20397,20398,20399

In [45]:
means = data[['Kaunas', 'Vilnius', 'Klaipėda']].mean()
print(means)

Kaunas      10191.0
Vilnius     10192.0
Klaipėda    10193.0
dtype: float64

In [47]:
no_first_column = data.drop(columns=['Birštonas'])
no_first_column

,Kaunas,Vilnius,Klaipėda,Biržai,Druskininkai,Prienai,Šiauliai,Alytus,Jonava,Kėdainiai,Kretinga,Kupiškis,Palanga,Šventoji,Marijampolė,Pakruojis,Panevėžys,Plungė,Rokiškis
0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
1,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39
2,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59
3,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79
4,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1015,20301,20302,20303,20304,20305,20306,20307,20308,20309,20310,20311,20312,20313,20314,20315,20316,20317,20318,20319
1016,20321,20322,20323,20324,20325,20326,20327,20328,20329,20330,20331,20332,20333,20334,20335,20336,20337,20338,20339
1017,20341,20342,20343,20344,20345,20346,20347,20348,20349,20350,20351,20352,20353,20354,20355,20356,20357,20358,20359
1018,20361,20362,20363,20364,20365,20366,20367,20368,20369,20370,20371,20372,20373,20374,20375,20376,20377,20378,20379
1019,20381,20382,20383,20384,20385,20386,20387,20388,20389,20390,20391,20392,20393,20394,20395,20396,20397,20398,20399

In [49]:
mean = no_first_column.mean()
mean

Kaunas          10191.0
Vilnius         10192.0
Klaipėda        10193.0
Biržai          10194.0
Druskininkai    10195.0
Prienai         10196.0
Šiauliai        10197.0
Alytus          10198.0
Jonava          10199.0
Kėdainiai       10200.0
Kretinga        10201.0
Kupiškis        10202.0
Palanga         10203.0
Šventoji        10204.0
Marijampolė     10205.0
Pakruojis       10206.0
Panevėžys       10207.0
Plungė          10208.0
Rokiškis        10209.0
dtype: float64

In [53]:
for column in data.columns:
    data[column] = data[column].mean()
data

,Birštonas,Kaunas,Vilnius,Klaipėda,Biržai,Druskininkai,Prienai,Šiauliai,Alytus,Jonava,Kėdainiai,Kretinga,Kupiškis,Palanga,Šventoji,Marijampolė,Pakruojis,Panevėžys,Plungė,Rokiškis
0,10190.0,10191.0,10192.0,10193.0,10194.0,10195.0,10196.0,10197.0,10198.0,10199.0,10200.0,10201.0,10202.0,10203.0,10204.0,10205.0,10206.0,10207.0,10208.0,10209.0
1,10190.0,10191.0,10192.0,10193.0,10194.0,10195.0,10196.0,10197.0,10198.0,10199.0,10200.0,10201.0,10202.0,10203.0,10204.0,10205.0,10206.0,10207.0,10208.0,10209.0
2,10190.0,10191.0,10192.0,10193.0,10194.0,10195.0,10196.0,10197.0,10198.0,10199.0,10200.0,10201.0,10202.0,10203.0,10204.0,10205.0,10206.0,10207.0,10208.0,10209.0
3,10190.0,10191.0,10192.0,10193.0,10194.0,10195.0,10196.0,10197.0,10198.0,10199.0,10200.0,10201.0,10202.0,10203.0,10204.0,10205.0,10206.0,10207.0,10208.0,10209.0
4,10190.0,10191.0,10192.0,10193.0,10194.0,10195.0,10196.0,10197.0,10198.0,10199.0,10200.0,10201.0,10202.0,10203.0,10204.0,10205.0,10206.0,10207.0,10208.0,10209.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1015,10190.0,10191.0,10192.0,10193.0,10194.0,10195.0,10196.0,10197.0,10198.0,10199.0,10200.0,10201.0,10202.0,10203.0,10204.0,10205.0,10206.0,10207.0,10208.0,10209.0
1016,10190.0,10191.0,10192.0,10193.0,10194.0,10195.0,10196.0,10197.0,10198.0,10199.0,10200.0,10201.0,10202.0,10203.0,10204.0,10205.0,10206.0,10207.0,10208.0,10209.0
1017,10190.0,10191.0,10192.0,10193.0,10194.0,10195.0,10196.0,10197.0,10198.0,10199.0,10200.0,10201.0,10202.0,10203.0,10204.0,10205.0,10206.0,10207.0,10208.0,10209.0
1018,10190.0,10191.0,10192.0,10193.0,10194.0,10195.0,10196.0,10197.0,10198.0,10199.0,10200.0,10201.0,10202.0,10203.0,10204.0,10205.0,10206.0,10207.0,10208.0,10209.0
1019,10190.0,10191.0,10192.0,10193.0,10194.0,10195.0,10196.0,10197.0,10198.0,10199.0,10200.0,10201.0,10202.0,10203.0,10204.0,10205.0,10206.0,10207.0,10208.0,10209.0

### Q2

1. Download stock data for top five biggest tech companies.
2. Save the collected data into a csv file.
3. Which company has the highest stock price as of last day?
4. Calcualte cross-correlation between the companies. 
5. If I can only choose two companies out of five which ones should I choose in order to have a diverse portfolio?

In [54]:
pip install yfinance

Requirement already satisfied: yfinance in c:\users\karol\anaconda3\lib\site-packages (0.2.37)
Requirement already satisfied: pandas>=1.3.0 in c:\users\karol\anaconda3\lib\site-packages (from yfinance) (2.0.3)
Requirement already satisfied: numpy>=1.16.5 in c:\users\karol\anaconda3\lib\site-packages (from yfinance) (1.24.3)
Requirement already satisfied: requests>=2.31 in c:\users\karol\anaconda3\lib\site-packages (from yfinance) (2.31.0)
Requirement already satisfied: multitasking>=0.0.7 in c:\users\karol\anaconda3\lib\site-packages (from yfinance) (0.0.9)
Requirement already satisfied: lxml>=4.9.1 in c:\users\karol\anaconda3\lib\site-packages (from yfinance) (4.9.3)
Requirement already satisfied: appdirs>=1.4.4 in c:\users\karol\anaconda3\lib\site-packages (from yfinance) (1.4.4)
Requirement already satisfied: pytz>=2022.5 in c:\users\karol\anaconda3\lib\site-packages (from yfinance) (2023.3.post1)
Requirement already satisfied: frozendict>=2.3.4 in c:\users\karol\anaconda3\lib\site-packages (from yfinance) (2.4.1)
Requirement already satisfied: peewee>=3.16.2 in c:\users\karol\anaconda3\lib\site-packages (from yfinance) (3.17.1)
Requirement already satisfied: beautifulsoup4>=4.11.1 in c:\users\karol\anaconda3\lib\site-packages (from yfinance) (4.12.2)
Requirement already satisfied: html5lib>=1.1 in c:\users\karol\anaconda3\lib\site-packages (from yfinance) (1.1)
Requirement already satisfied: soupsieve>1.2 in c:\users\karol\anaconda3\lib\site-packages (from beautifulsoup4>=4.11.1->yfinance) (2.4)
Requirement already satisfied: six>=1.9 in c:\users\karol\anaconda3\lib\site-packages (from html5lib>=1.1->yfinance) (1.16.0)
Requirement already satisfied: webencodings in c:\users\karol\anaconda3\lib\site-packages (from html5lib>=1.1->yfinance) (0.5.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\karol\anaconda3\lib\site-packages (from pandas>=1.3.0->yfinance) (2.8.2)
Requirement already satisfied: tzdata>=2022.1 in c:\users\karol\anaconda3\lib\site-packages (from pandas>=1.3.0->yfinance) (2023.3)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\karol\anaconda3\lib\site-packages (from requests>=2.31->yfinance) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\karol\anaconda3\lib\site-packages (from requests>=2.31->yfinance) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\karol\anaconda3\lib\site-packages (from requests>=2.31->yfinance) (1.26.16)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\karol\anaconda3\lib\site-packages (from requests>=2.31->yfinance) (2024.2.2)
Note: you may need to restart the kernel to use updated packages.

In [55]:
import yfinance as yf

In [68]:
ticker_symbols = ['AAPL', 'MSFT', 'AMZN', 'META', 'GOOGL']
stock_data = yf.download(ticker_symbols, start='2023-01-01', end='2023-12-31')
stock_data

[*********************100%%**********************]  5 of 5 completed

Price        Adj Close                                                  \
Ticker            AAPL        AMZN       GOOGL        META        MSFT
Date
2023-01-03  124.216293   85.820000   89.120003  124.607788  237.035995
2023-01-04  125.497498   85.139999   88.080002  127.235008  226.667282
2023-01-05  124.166641   83.120003   86.199997  126.805458  219.949387
2023-01-06  128.735245   86.080002   87.339996  129.882202  222.541565
2023-01-09  129.261627   87.360001   88.019997  129.332779  224.708282
...                ...         ...         ...         ...         ...
2023-12-22  193.353287  153.419998  141.490005  353.015472  373.888580
2023-12-26  192.803986  153.410004  141.520004  354.453918  373.968445
2023-12-27  192.903839  153.339996  140.369995  357.450714  373.379547
2023-12-28  193.333298  153.380005  140.229996  357.940216  374.587280
2023-12-29  192.284637  151.940002  139.690002  353.584839  375.345886

Price            Close                                                  ...  \
Ticker            AAPL        AMZN       GOOGL        META        MSFT  ...
Date                                                                    ...
2023-01-03  125.070000   85.820000   89.120003  124.739998  239.580002  ...
2023-01-04  126.360001   85.139999   88.080002  127.370003  229.100006  ...
2023-01-05  125.019997   83.120003   86.199997  126.940002  222.309998  ...
2023-01-06  129.619995   86.080002   87.339996  130.020004  224.929993  ...
2023-01-09  130.149994   87.360001   88.019997  129.470001  227.119995  ...
...                ...         ...         ...         ...         ...  ...
2023-12-22  193.600006  153.419998  141.490005  353.390015  374.579987  ...
2023-12-26  193.050003  153.410004  141.520004  354.829987  374.660004  ...
2023-12-27  193.149994  153.339996  140.369995  357.829987  374.070007  ...
2023-12-28  193.580002  153.380005  140.229996  358.320007  375.279999  ...
2023-12-29  192.529999  151.940002  139.690002  353.959991  376.040009  ...

Price             Open                                                  \
Ticker            AAPL        AMZN       GOOGL        META        MSFT
Date
2023-01-03  130.279999   85.459999   89.589996  122.820000  243.080002
2023-01-04  126.889999   86.550003   90.349998  127.379997  232.279999
2023-01-05  127.129997   85.330002   87.470001  126.129997  227.199997
2023-01-06  126.010002   83.029999   86.790001  128.970001  223.000000
2023-01-09  130.470001   87.459999   88.360001  131.160004  226.449997
...                ...         ...         ...         ...         ...
2023-12-22  195.179993  153.770004  140.770004  355.579987  373.679993
2023-12-26  193.610001  153.559998  141.589996  354.989990  375.000000
2023-12-27  192.490005  153.559998  141.589996  356.070007  373.690002
2023-12-28  194.139999  153.720001  140.779999  359.700012  375.369995
2023-12-29  193.899994  153.100006  139.630005  358.989990  376.000000

Price          Volume
Ticker           AAPL      AMZN     GOOGL      META      MSFT
Date
2023-01-03  112117500  76706000  28131200  35528500  25740000
2023-01-04   89113600  68885100  34854800  32397100  50623400
2023-01-05   80962700  67930800  27194400  25447100  39585600
2023-01-06   87754700  83303400  41381500  27584500  43613600
2023-01-09   70790800  65266100  29003900  26649100  27369800
...               ...       ...       ...       ...       ...
2023-12-22   37122800  29480100  26514600  11764200  17091100
2023-12-26   28919300  25067200  16780300   9898600  12673100
2023-12-27   48087700  31434700  19628600  13207900  14905400
2023-12-28   34049900  27057000  16045700  11798800  14327000
2023-12-29   42628800  39789000  18727200  14980500  18723000

[250 rows x 30 columns]

In [62]:
stock_data.to_csv('top_five_tech_companies_stock_data.csv')

In [66]:
last_day_close = stock_data.iloc[-1]['Close']
company_highest_price = last_day_close.idxmax()
highest_price = last_day_close.max()

print("Company:", company_highest_price)
print("Stock Price:", highest_price)

Company: MSFT
Stock Price: 376.0400085449219

In [67]:
close_prices = stock_data['Close']
correlation_matrix = close_prices.corr()
print(correlation_matrix)

Ticker      AAPL      AMZN     GOOGL      META      MSFT
Ticker
AAPL    1.000000  0.881090  0.851049  0.927491  0.947791
AMZN    0.881090  1.000000  0.939586  0.951626  0.936043
GOOGL   0.851049  0.939586  1.000000  0.953250  0.897546
META    0.927491  0.951626  0.953250  1.000000  0.957793
MSFT    0.947791  0.936043  0.897546  0.957793  1.000000

In [70]:
#5. If I can only choose two companies out of five which ones should I choose in order to have a diverse portfolio?
#I would choose GOOGL and AAPL because these two companies have the lowest correlation with each other.