# DATA LOADING

### EX. 1

Import a random csv file into python.

In [2]:
import pandas as pd
pd.read_csv('data/examples/ex1.csv')

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

### EX. 2

Import a random csv file that changes its columns into index.

In [3]:
names = ['a', 'b', 'c', 'd', 'message']
pd.read_csv('data/examples/ex2.csv', names=names, index_col='message')

         a   b   c   d
message
hello    1   2   3   4
world    5   6   7   8
foo      9  10  11  12

### EX. 3

Import a large csv file and display 100 rows.

In [6]:
box = pd.read_csv('data/examples/ex6.csv')

In [9]:
pd.set_option('display.min_rows', 101)

In [10]:
box.head(100)

         one       two     three      four key
0   0.467976 -0.038649 -0.295344 -1.824726   L
1  -0.358893  1.404453  0.704965 -0.200638   B
2  -0.501840  0.659254 -0.421691 -0.057688   G
3   0.204886  1.074134  1.388361 -0.982404   R
4   0.354628 -0.133116  0.283763 -0.837063   Q
5   1.817480  0.742273  0.419395 -2.251035   Q
6  -0.776764  0.935518 -0.332872 -1.875641   U
7  -0.913135  1.530624 -0.572657  0.477252   K
8   0.358480 -0.497572 -0.367016  0.507702   S
9  -1.740877 -1.160417 -1.637830  2.172201   G
10  0.240564 -0.328249  1.252155  1.072796   8
11  0.764018  1.165476 -0.639544  1.495258   R
12  0.571035 -0.310537  0.582437 -0.298765   1
13  2.317658  0.430710 -1.334216  0.199679   P
14  1.547771 -1.119753 -2.277634  0.329586   J
15 -1.310608  0.401719 -1.000987  1.156708   E
16 -0.088496  0.634712  0.153324  0.415335   B
17 -0.018663 -0.247487 -1.446522  0.750938   A
18 -0.070127 -1.579097  0.120892  0.671432   F
19 -0.194678 -0.492039  2.359605  0.319810   H
20 -0.248618  0.868707 -0.492226 -0.717959   W
21 -1.091549 -0.867110 -0.647760 -0.832562   C
22  0.641404 -0.138822 -0.621963 -0.284839   C
23  1.216408  0.992687  0.165162 -0.069619   V
24 -0.564474  0.792832  0.747053  0.571675   I
25  1.759879 -0.515666 -0.230481  1.362317   S
26  0.126266  0.309281  0.382820 -0.239199   L
27  1.334360 -0.100152 -0.840731 -0.643967   6
28 -0.737620  0.278087 -0.053235 -0.950972   J
29 -1.148486 -0.986292 -0.144963  0.124362   Y
..       ...       ...       ...       ...  ..
70  1.809750  0.592023 -0.146215 -0.113818   J
71  0.190562 -2.886359  0.514365 -2.208118   F
72  0.844977 -0.164290  0.218672  0.099012   D
73  0.195035 -0.649591  2.171664  0.453466   I
74 -0.056433  1.758650 -0.448091  0.346784   C
75 -0.112609 -2.642457 -0.487310 -0.220507   K
76 -1.395319  0.573474 -0.013324 -1.307070   C
77 -2.080273  0.097498  0.321489  0.012608   E
78  0.883172  0.490427 -0.799299 -0.699669   U
79 -0.138632 -1.417845 -0.199678  1.199299   V
80 -0.961579  1.166247 -1.124953  0.201728   D
81  1.301453  1.077117  0.560502  0.859991   U
82  0.063679 -0.995532  0.879547 -0.012471   R
83 -0.373381  0.982861 -0.037534 -1.337856   G
84  1.492292  0.485490  0.129313  1.733569   Y
85 -0.908492  0.498234 -0.588844 -0.903956   8
86  1.137140  0.977509 -0.940994  0.149013   7
87 -1.049838  2.453425  1.230087 -2.068508   K
88  1.485199 -0.806453 -0.475087  0.936801   D
89 -0.790437  1.823852  0.470827  0.898782   J
90  2.024808  0.032251  1.315297 -0.156433   S
91  0.379253 -1.059409 -1.132068  1.222296   I
92  2.403216 -1.792528 -0.917573 -0.886693   T
93  1.249975  1.491530  0.371476 -0.000465   C
94  0.501131 -1.852451  1.110354  0.508865   E
95  1.106521  0.098153  0.789793  1.192693   T
96 -0.540543  1.782569  0.051931  0.463868   Q
97 -0.101980  0.981720  1.106990 -1.752269   M
98  0.632107 -0.761419  1.427930 -0.046928   F
99  1.009779 -0.608379 -1.405105 -1.175054   F

[100 rows x 5 columns]

### EX. 4

Read a csv file in pieces. Chuksizes.

### EX. 5

Export csv file with a different seperator.For example "|".

### EX. 6

Import the jaosn file.

obj = """
{"name": "Wes",
 "places_lived": ["United States", "Spain", "Germany"],
 "pet": null,
 "siblings": [{"name": "Scott", "age": 30, "pets": ["Zeus", "Zuko"]},
              {"name": "Katie", "age": 38,
               "pets": ["Sixes", "Stache", "Cisco"]}]
}

Retrieve the age of Katie.

### EX.7

Convert a jason file into dataframe using the siblings values. 

Import the json file.

obj = """
{"name": "Wes",
 "places_lived": ["United States", "Spain", "Germany"],
 "pet": null,
 "siblings": [{"name": "Scott", "age": 30, "pets": ["Zeus", "Zuko"]},
              {"name": "Katie", "age": 38,
               "pets": ["Sixes", "Stache", "Cisco"]}]
}

### EX. 8

Download apple prices from yahoo api.

### EX. 9

Download data from worldbank for multiple countries and mutiple indicators.

### EX. 10

Import a random excel file into a dataframe.