# PANDAS

In [3]:
import pandas as pd
import numpy as np

### EX. 1

Create a pandas series with indexes 0 to 10 and values 20 to 30

In [4]:
np.arange(20,30)

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [5]:
list(range(20, 30))

[20, 21, 22, 23, 24, 25, 26, 27, 28, 29]

In [6]:
pd.Series(list(range(20, 30)), index=np.arange(0,10))

0    20
1    21
2    22
3    23
4    24
5    25
6    26
7    27
8    28
9    29
dtype: int64

### EX. 2

Create a pandas series with indexes a to e and values 1 to 5

In [7]:
pd.Series([1,2,3,4,5], index=['a', 'b', 'c', 'd', 'e'])

a    1
b    2
c    3
d    4
e    5
dtype: int64

### EX. 3

Create a pandas series with indexes a to e and values 1 to 5. When save the series in to data_1 object. Copy data_1 into data_2 object. Change the index value of a to 9999

In [8]:
data_1 = pd.Series([1,2,3,4,5], index=['a', 'b', 'c', 'd', 'e'])
data_2 = data_1.copy()
data_2['a'] = 9999
data_2

a    9999
b       2
c       3
d       4
e       5
dtype: int64

### EX. 4

Create a pandas series with indexes a to e and values 1 to 5. Filter values that are lower than 2.

In [9]:
box = pd.Series(np.arange(1,6), index=['a', 'b', 'c', 'd', 'e'])

In [10]:
box[box < 2]

a    1
dtype: int32

### EX. 5

Create a series from a dictionary. Change the index of a series into country names 'California', 'Ohio', 'Oregon', 'Texas'.

In [11]:
box = pd.Series({'bob': 2, 'go':4, 'low': 4,'oops': 4})

In [12]:
box.index = [ 'California', 'Ohio', 'Oregon', 'Texas']

In [13]:
box

California    2
Ohio          4
Oregon        4
Texas         4
dtype: int64

### EX. 6

Create a dataframe with ten columns and 25 values. Indexes must be from zero to 25.

In [14]:
box = np.random.rand(26, 11)

In [15]:
pd.DataFrame(np.random.rand(26, 11)) #26 eilutes 11 stulpeliu

,0,1,2,3,4,5,6,7,8,9,10
0,0.801952,0.238493,0.667788,0.549313,0.607270,0.367124,0.236090,0.070130,0.287934,0.450462,0.735751
1,0.265819,0.637921,0.251321,0.060622,0.193230,0.351692,0.286995,0.001923,0.675732,0.524261,0.057021
2,0.960363,0.136497,0.384001,0.432175,0.164130,0.716531,0.354856,0.531336,0.955380,0.448741,0.129669
3,0.389887,0.313696,0.705200,0.135659,0.384724,0.823979,0.679491,0.514748,0.000853,0.380186,0.204856
4,0.452398,0.120358,0.285452,0.270406,0.928187,0.363817,0.468892,0.084363,0.267094,0.100703,0.928671
5,0.514506,0.059792,0.796477,0.134279,0.131651,0.332845,0.900937,0.606467,0.747651,0.557163,0.665002
6,0.201973,0.418083,0.920348,0.687320,0.241962,0.944068,0.608576,0.218243,0.828778,0.649818,0.485668
7,0.772993,0.610861,0.097069,0.458107,0.328755,0.175593,0.482078,0.677657,0.568621,0.052614,0.570288
8,0.259658,0.207663,0.336007,0.137833,0.770112,0.364141,0.411020,0.265651,0.275101,0.735671,0.657176
9,0.500751,0.211177,0.306696,0.721609,0.146395,0.332289,0.258904,0.894960,0.060954,0.651667,0.858790
10,0.960789,0.987842,0.612264,0.635958,0.137991,0.066456,0.247490,0.676961,0.839120,0.102910,0.363849
11,0.807546,0.101330,0.279567,0.749988,0.192197,0.191126,0.861934,0.962667,0.703678,0.754023,0.924866
12,0.313745,0.090273,0.526296,0.765430,0.264136,0.573769,0.681099,0.615997,0.395373,0.146438,0.395737
13,0.588195,0.041000,0.086660,0.379194,0.571777,0.961772,0.332544,0.537365,0.275564,0.124293,0.124930
14,0.061885,0.365021,0.669202,0.792956,0.722339,0.818634,0.470137,0.761752,0.317232,0.804820,0.268003
15,0.238887,0.541735,0.715930,0.544086,0.345797,0.596614,0.222507,0.098882,0.230373,0.360367,0.222131
16,0.232253,0.939463,0.873484,0.590144,0.106583,0.944216,0.126926,0.026380,0.620792,0.259240,0.494349
17,0.881174,0.946268,0.855869,0.702666,0.195916,0.916644,0.109357,0.512483,0.222401,0.573476,0.542922
18,0.984825,0.710510,0.086286,0.164380,0.238817,0.391427,0.639109,0.249542,0.203012,0.628417,0.858045
19,0.270056,0.992359,0.866003,0.579722,0.943615,0.391005,0.280887,0.733104,0.163691,0.994896,0.967638
20,0.906833,0.847561,0.504595,0.930901,0.547536,0.503738,0.966341,0.336308,0.145011,0.312841,0.602190
21,0.888209,0.821881,0.533846,0.858150,0.594479,0.460167,0.233497,0.079221,0.335885,0.625902,0.192142
22,0.774910,0.637492,0.392741,0.609239,0.498126,0.407997,0.539873,0.406532,0.389330,0.780302,0.413069
23,0.354033,0.114850,0.443785,0.321615,0.359738,0.688003,0.116719,0.821362,0.829817,0.733106,0.185207
24,0.889822,0.343335,0.513467,0.217643,0.941257,0.657694,0.235450,0.446236,0.845237,0.595930,0.840674
25,0.217854,0.547641,0.415869,0.933293,0.677154,0.238484,0.009996,0.317649,0.636936,0.589358,0.025646

In [16]:
pd.DataFrame(np.random.rand(11, 26))

,0,1,2,3,4,5,6,7,8,9,...,16,17,18,19,20,21,22,23,24,25
0,0.980674,0.073665,0.557248,0.370315,0.542446,0.519106,0.379324,0.410919,0.474036,0.902919,...,0.291528,0.209638,0.855800,0.613084,0.427627,0.619634,0.157782,0.697166,0.272284,0.003235
1,0.151355,0.511458,0.060632,0.746152,0.210047,0.067802,0.652724,0.821467,0.159892,0.865520,...,0.313815,0.158469,0.105254,0.431438,0.363181,0.020861,0.288469,0.546697,0.551224,0.620434
2,0.212693,0.234963,0.704496,0.207575,0.587448,0.544868,0.251876,0.277162,0.353446,0.423586,...,0.848441,0.086975,0.473617,0.308979,0.555189,0.778028,0.785739,0.114868,0.106397,0.148666
3,0.897892,0.676431,0.872016,0.230292,0.376327,0.811606,0.875644,0.133071,0.919135,0.493683,...,0.952660,0.636765,0.667481,0.726058,0.848557,0.305421,0.601805,0.740763,0.310959,0.861305
4,0.333462,0.093053,0.424064,0.305303,0.738342,0.108863,0.301568,0.797421,0.460691,0.231553,...,0.443354,0.680423,0.150595,0.202907,0.976733,0.126906,0.949518,0.474549,0.014680,0.463387
5,0.748628,0.831084,0.492814,0.337629,0.949281,0.870541,0.828269,0.309318,0.820265,0.303500,...,0.439386,0.493704,0.455365,0.325141,0.831815,0.866845,0.304145,0.600530,0.384762,0.768910
6,0.031570,0.284890,0.437239,0.738745,0.538692,0.843534,0.391689,0.514109,0.469961,0.234661,...,0.769750,0.998569,0.031290,0.328215,0.184694,0.540088,0.732760,0.196580,0.705724,0.223580
7,0.736797,0.630618,0.919258,0.132570,0.187749,0.003718,0.416716,0.549049,0.677063,0.078382,...,0.561143,0.594560,0.527020,0.573983,0.408603,0.120889,0.469287,0.021261,0.419441,0.609775
8,0.442235,0.505830,0.058668,0.237354,0.011867,0.579073,0.052381,0.119131,0.170808,0.962330,...,0.016878,0.661318,0.518867,0.722714,0.416506,0.708663,0.526348,0.282615,0.496368,0.606887
9,0.121751,0.714012,0.501366,0.264842,0.083335,0.794470,0.548589,0.944379,0.685942,0.582891,...,0.133974,0.814746,0.182970,0.401798,0.524751,0.148970,0.606469,0.679875,0.887975,0.376689
10,0.812194,0.714225,0.730091,0.947418,0.510494,0.434284,0.045712,0.716039,0.715729,0.058052,...,0.293539,0.841466,0.689545,0.973842,0.329522,0.166724,0.565546,0.442837,0.512981,0.924279

### EX.7

Create a dataframe with an Nan value. Use function is null to check the boolean value. Change the values of Nan into 5. Print each step in a seperate line.

In [27]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9},
       'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}
frame = pd.DataFrame(pop)
frame

      Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [30]:
pd.isnull(frame)

      Nevada   Ohio
2001   False  False
2002   False  False
2000    True  False

In [31]:
frame['Nevada'] = {2001: 2.4, 2002: 2.9, 2000: 2.5}
frame

      Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     2.5   1.5

### EX. 10

Create a datfarame with ten columns and ten values. Index only the 5 to 10 values.

In [49]:
frame = pd.DataFrame(np.arange(1,11).reshape((1, 10)), 
                     columns=['year', 'state', 'pop', 'debt', 'labas', 'ate', 'ok', 'sdf', 'ads', 'RGb'],
                     index = ['one'])
frame

     year  state  pop  debt  labas  ate  ok  sdf  ads  RGb
one     1      2    3     4      5    6   7    8    9   10