# Data Loading, Storage,

In [ ]:
import sys
!conda install --yes --prefix {sys.prefix} -c conda-forge yfinance
#!{sys.executable} -m pip install yfinance

In [ ]:
import numpy as np
import pandas as pd

## Reading and Writing Data in Text Format

Handling dates and other custom types can require extra effort. Let’s start with a small comma-separated (CSV) text file

Here I used the Unix cat shell command to print the raw contents of the file to the screen. If you’re on Windows, you can use type instead of cat to achieve the same effect. Since this is comma-delimited, we can use read_csv to read it into a DataFrame:

In [7]:
df = pd.read_csv('examples-20240404/examples/ex1.csv')
df

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

We could also have used read_table and specified the delimiter

In [9]:
pd.read_table('examples-20240404/examples/ex1.csv', sep=',')

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

A file will not always have a header row. Consider this file

In [10]:
!cat examples-20240404/examples/ex1.csv

'cat' is not recognized as an internal or external command,
operable program or batch file.

To read this file, you have a couple of options. You can allow pandas to assign default column names, or you can specify names yourself

In [11]:
pd.read_csv('examples-20240404/examples/ex2.csv', header=None)

   0   1   2   3      4
0  1   2   3   4  hello
1  5   6   7   8  world
2  9  10  11  12    foo

In [12]:
pd.read_csv('examples-20240404/examples/ex2.csv', names=['a', 'b', 'c', 'd', 'message'])

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

Suppose you wanted the message column to be the index of the returned DataFrame. You can either indicate you want the column at index 4 or named 'message' using the index_col argument

In [13]:
names = ['a', 'b', 'c', 'd', 'message']
pd.read_csv('examples-20240404/examples/ex2.csv', names=names, index_col='message')

         a   b   c   d
message
hello    1   2   3   4
world    5   6   7   8
foo      9  10  11  12

In the event that you want to form a hierarchical index from multiple columns, pass a list of column numbers or names

In [ ]:
!cat data/examples/csv_mindex.csv

In [16]:
parsed = pd.read_csv('examples-20240404/examples/csv_mindex.csv',
                     index_col=['key1', 'key2'])
parsed

           value1  value2
key1 key2
one  a          1       2
     b          3       4
     c          5       6
     d          7       8
two  a          9      10
     b         11      12
     c         13      14
     d         15      16

In some cases, a table might not have a fixed delimiter, using whitespace or some other pattern to separate fields. Consider a text file that looks like this

In [17]:
list(open('examples-20240404/examples/ex3.txt'))

['            A         B         C\n',
 'aaa -0.264438 -1.026059 -0.619500\n',
 'bbb  0.927272  0.302904 -0.032399\n',
 'ccc -0.264273 -0.386314 -0.217601\n',
 'ddd -0.871858 -0.348382  1.100491\n']

While you could do some munging by hand, the fields here are separated by a variable amount of whitespace. In these cases, you can pass a regular expression as a delimiter for read_table. This can be expressed by the regular expression \s+, so we have then

In [18]:
result = pd.read_table('examples-20240404/examples/ex3.txt', sep='\s+')
result

            A         B         C
aaa -0.264438 -1.026059 -0.619500
bbb  0.927272  0.302904 -0.032399
ccc -0.264273 -0.386314 -0.217601
ddd -0.871858 -0.348382  1.100491

Because there was one fewer column name than the number of data rows, read_table infers that the first column should be the DataFrame’s index in this special case.
The parser functions have many additional arguments to help you handle the wide variety of exception file formats that occur (see a partial listing in Table 6-2). For example, you can skip the first, third, and fourth rows of a file with skiprows

In [19]:
!cat data/examples/ex4.csv
pd.read_csv('examples-20240404/examples/ex4.csv', skiprows=[0, 2, 3])

'cat' is not recognized as an internal or external command,
operable program or batch file.

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

Handling missing values is an important and frequently nuanced part of the file parsing process. Missing data is usually either not present (empty string) or marked by some sentinel value. By default, pandas uses a set of commonly occurring sentinels, such as NA and NULL

In [20]:
!cat data/examples/ex5.csv
result = pd.read_csv('examples-20240404/examples/ex5.csv')
result

'cat' is not recognized as an internal or external command,
operable program or batch file.

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo

In [21]:
pd.isnull(result)

   something      a      b      c      d  message
0      False  False  False  False  False     True
1      False  False  False   True  False    False
2      False  False  False  False  False    False

The na_values option can take either a list or set of strings to consider missing values

In [22]:
result = pd.read_csv('examples-20240404/examples/ex5.csv', na_values=['NULL'])
result

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo

Different NA sentinels can be specified for each column in a dict

In [23]:
sentinels = {'message': ['foo', 'NA'], 'something': ['two']}
pd.read_csv('examples-20240404/examples/ex5.csv', na_values=sentinels)

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       NaN  5   6   NaN   8   world
2     three  9  10  11.0  12     NaN

### Reading Text Files in Pieces

When processing very large files or figuring out the right set of arguments to correctly process a large file, you may only want to read in a small piece of a file or iterate through smaller chunks of the file.
Before we look at a large file, we make the pandas display settings more compact

In [27]:
pd.set_option('display.max_columns', 6)
pd.set_option('display.max_rows', 200) ### if we have 1000 and we ask for 200 we will only see five rows unless we set max_rows = 1000
pd.set_option('display.min_rows', 5) ### Will always display this number
pd.set_option('display.expand_frame_repr', True)

In [28]:
pd.set_option('display.min_rows', 10)

In [29]:
result = pd.read_csv('examples-20240404/examples/ex6.csv')
result

           one       two     three      four key
0     0.467976 -0.038649 -0.295344 -1.824726   L
1    -0.358893  1.404453  0.704965 -0.200638   B
2    -0.501840  0.659254 -0.421691 -0.057688   G
3     0.204886  1.074134  1.388361 -0.982404   R
4     0.354628 -0.133116  0.283763 -0.837063   Q
...        ...       ...       ...       ...  ..
9995  2.311896 -0.417070 -1.409599 -0.515821   L
9996 -0.479893 -0.650419  0.745152 -0.646038   E
9997  0.523331  0.787112  0.486066  1.093156   K
9998 -0.362559  0.598894 -1.843201  0.887292   G
9999 -0.096376 -1.012999 -0.657431 -0.573315   0

[10000 rows x 5 columns]

If you want to only read a small number of rows (avoiding reading the entire file), specify that with nrows

In [30]:
pd.read_csv('examples-20240404/examples/ex6.csv', nrows=10)

        one       two     three      four key
0  0.467976 -0.038649 -0.295344 -1.824726   L
1 -0.358893  1.404453  0.704965 -0.200638   B
2 -0.501840  0.659254 -0.421691 -0.057688   G
3  0.204886  1.074134  1.388361 -0.982404   R
4  0.354628 -0.133116  0.283763 -0.837063   Q
5  1.817480  0.742273  0.419395 -2.251035   Q
6 -0.776764  0.935518 -0.332872 -1.875641   U
7 -0.913135  1.530624 -0.572657  0.477252   K
8  0.358480 -0.497572 -0.367016  0.507702   S
9 -1.740877 -1.160417 -1.637830  2.172201   G

To read a file in pieces, specify a chunksize as a number of rows

In [31]:
chunker = pd.read_csv('examples-20240404/examples/ex6.csv', chunksize=1000)
chunker

The TextParser object returned by read_csv allows you to iterate over the parts of the file according to the chunksize. For example, we can iterate over ex6.csv, aggregating the value counts in the 'key' column like so

In [36]:
chunker = pd.read_csv('examples-20240404/examples/ex6.csv', chunksize=1000)

tot = pd.Series([])
for piece in chunker:
    tot = tot.add(piece['key'].value_counts(), fill_value=0)

tot = tot.sort_values(ascending=False)

In [35]:
piece

           one       two     three      four key
9000  0.467976 -0.038649 -0.295344 -1.824726   B
9001 -0.358893  1.404453  0.704965 -0.200638   M
9002 -0.501840  0.659254 -0.421691 -0.057688   N
9003  0.204886  1.074134  1.388361 -0.982404   N
9004  0.354628 -0.133116  0.283763 -0.837063   Y
...        ...       ...       ...       ...  ..
9995  2.311896 -0.417070 -1.409599 -0.515821   L
9996 -0.479893 -0.650419  0.745152 -0.646038   E
9997  0.523331  0.787112  0.486066  1.093156   K
9998 -0.362559  0.598894 -1.843201  0.887292   G
9999 -0.096376 -1.012999 -0.657431 -0.573315   0

[1000 rows x 5 columns]

In [37]:
tot

key
E    368
X    364
L    346
O    343
Q    340
M    338
J    337
F    335
K    334
H    330
V    328
I    327
U    326
P    324
D    320
A    320
R    318
Y    314
G    308
S    308
N    306
W    305
T    304
B    302
Z    288
C    286
4    171
6    166
7    164
8    162
3    162
5    157
2    152
0    151
9    150
1    146
dtype: object

### Writing Data to Text Format

Data can also be exported to a delimited format. Let’s consider one of the CSV files read before

In [38]:
data = pd.read_csv('examples-20240404/examples/ex5.csv')
data

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo

Using DataFrame’s to_csv method, we can write the data out to a comma-separated file

In [39]:
data.to_csv('examples-20240404/examples/out_2.csv')
!cat data/examples/out.csv

'cat' is not recognized as an internal or external command,
operable program or batch file.

Other delimiters can be used, of course (writing to sys.stdout so it prints the text result to the console)

In [40]:
import sys
data.to_csv(sys.stdout, sep='|')

|something|a|b|c|d|message
0|one|1|2|3.0|4|
1|two|5|6||8|world
2|three|9|10|11.0|12|foo

Missing values appear as empty strings in the output. You might want to denote them by some other sentinel value

In [41]:
data.to_csv(sys.stdout, na_rep='NULL')

,something,a,b,c,d,message
0,one,1,2,3.0,4,NULL
1,two,5,6,NULL,8,world
2,three,9,10,11.0,12,foo

With no other options specified, both the row and column labels are written. Both of these can be disabled

In [42]:
data.to_csv(sys.stdout, index=False, header=False)

one,1,2,3.0,4,
two,5,6,,8,world
three,9,10,11.0,12,foo

You can also write only a subset of the columns, and in an order of your choosing:

In [43]:
data.to_csv(sys.stdout, index=False, columns=['a', 'b', 'c'])

a,b,c
1,2,3.0
5,6,
9,10,11.0

Series also has a to_csv method

In [44]:
dates = pd.date_range('1/1/2000', periods=7)
ts = pd.Series(np.arange(7), index=dates)
ts

2000-01-01    0
2000-01-02    1
2000-01-03    2
2000-01-04    3
2000-01-05    4
2000-01-06    5
2000-01-07    6
Freq: D, dtype: int32

In [45]:
dates = pd.date_range('1/1/2000', periods=7)
ts = pd.Series(np.arange(7), index=dates)
ts.to_csv('examples-20240404/examples/tseries.csv')
!cat data/examples/tseries.csv

'cat' is not recognized as an internal or external command,
operable program or batch file.

### Working with Delimited Formats

It’s possible to load most forms of tabular data from disk using functions like pandas.read_table. In some cases, however, some manual processing may be necessary. It’s not uncommon to receive a file with one or more malformed lines that trip up read_table. To illustrate the basic tools, consider a small CSV file

In [ ]:
!cat data/examples/ex7.csv

For any file with a single-character delimiter, you can use Python’s built-in csv module. To use it, pass any open file or file-like object to csv.reader

In [46]:
import csv
f = open('examples-20240404/examples/ex7.csv')

reader = csv.reader(f)
reader

Iterating through the reader like a file yields tuples of values with any quote characters removed:

In [47]:
for line in reader:
    print(line)

['a', 'b', 'c']
['1', '2', '3']
['1', '2', '3']

From there, it’s up to you to do the wrangling necessary to put the data in the form that you need it. Let’s take this step by step. First, we read the file into a list of lines

In [48]:
with open('examples-20240404/examples/ex7.csv') as f:
    lines = list(csv.reader(f))

Then, we split the lines into the header line and the data lines:

In [49]:
header, values = lines[0], lines[1:]

In [50]:
lines[0]

['a', 'b', 'c']

### JSON Data

JSON (short for JavaScript Object Notation) has become one of the standard formats for sending data by HTTP request between web browsers and other applications. It is a much more free-form data format than a tabular text form like CSV. Here is an example

In [51]:
obj = """
{"name": "Wes",
 "places_lived": ["United States", "Spain", "Germany"],
 "pet": null,
 "siblings": [{"name": "Scott", "age": 30, "pets": ["Zeus", "Zuko"]},
              {"name": "Katie", "age": 38,
               "pets": ["Sixes", "Stache", "Cisco"]}]
}
"""

JSON is very nearly valid Python code with the exception of its null value null and some other nuances (such as disallowing trailing commas at the end of lists). The basic types are objects (dicts), arrays (lists), strings, numbers, booleans, and nulls. All of the keys in an object must be strings. There are several Python libraries for reading
and writing JSON data. I’ll use json here, as it is built into the Python standard library. To convert a JSON string to Python form, use json.loads

In [52]:
import json
result = json.loads(obj)
result

{'name': 'Wes',
 'places_lived': ['United States', 'Spain', 'Germany'],
 'pet': None,
 'siblings': [{'name': 'Scott', 'age': 30, 'pets': ['Zeus', 'Zuko']},
  {'name': 'Katie', 'age': 38, 'pets': ['Sixes', 'Stache', 'Cisco']}]}

In [53]:
result['siblings'][0]['age']

30

json.dumps, on the other hand, converts a Python object back to JSON

In [54]:
asjson = json.dumps(result)

In [55]:
asjson

'{"name": "Wes", "places_lived": ["United States", "Spain", "Germany"], "pet": null, "siblings": [{"name": "Scott", "age": 30, "pets": ["Zeus", "Zuko"]}, {"name": "Katie", "age": 38, "pets": ["Sixes", "Stache", "Cisco"]}]}'

How you convert a JSON object or list of objects to a DataFrame or some other data structure for analysis will be up to you. Conveniently, you can pass a list of dicts (which were previously JSON objects) to the DataFrame constructor and select a subset of the data fields

In [56]:
siblings = pd.DataFrame(result['siblings'], columns=['name', 'age'])
siblings

    name  age
0  Scott   30
1  Katie   38

The pandas.read_json can automatically convert JSON datasets in specific arrangements into a Series or DataFrame. For example

In [57]:
!cat data/examples/example.json

'cat' is not recognized as an internal or external command,
operable program or batch file.

The default options for pandas.read_json assume that each object in the JSON array is a row in the table:

In [59]:
data = pd.read_json('examples-20240404/examples/example.json')
data

   a  b  c
0  1  2  3
1  4  5  6
2  7  8  9

For an extended example of reading and manipulating JSON data (including nested records), see the USDA Food Database example in Chapter 7.
If you need to export data from pandas to JSON, one way is to use the to_json meth‐ ods on Series and DataFrame

In [60]:
print(data.to_json())
print(data.to_json(orient='records'))

{"a":{"0":1,"1":4,"2":7},"b":{"0":2,"1":5,"2":8},"c":{"0":3,"1":6,"2":9}}
[{"a":1,"b":2,"c":3},{"a":4,"b":5,"c":6},{"a":7,"b":8,"c":9}]

### Reading Microsoft Excel Files

pandas also supports reading tabular data stored in Excel 2003 (and higher) files using either the ExcelFile class or pandas.read_excel function. Internally these tools use the add-on packages xlrd and openpyxl to read XLS and XLSX files, respectively. You may need to install these manually with pip or conda.
To use ExcelFile, create an instance by passing a path to an xls or xlsx file:

In [61]:
xlsx = pd.ExcelFile('examples-20240404/examples/ex1.xlsx')

In [62]:
openpyxl

NameError: name 'openpyxl' is not defined

Data stored in a sheet can then be read into DataFrame with parse:

In [69]:
import openpyxl
pd.read_excel(xlsx, 'Sheet1')

   Unnamed: 0  a   b   c   d message
0           0  1   2   3   4   hello
1           1  5   6   7   8   world
2           2  9  10  11  12     foo

If you are reading multiple sheets in a file, then it is faster to create the ExcelFile, but you can also simply pass the filename to pandas.read_excel

In [70]:
frame = pd.read_excel('examples-20240404/examples/ex1.xlsx', 'Sheet1')
frame

   Unnamed: 0  a   b   c   d message
0           0  1   2   3   4   hello
1           1  5   6   7   8   world
2           2  9  10  11  12     foo

To write pandas data to Excel format, you must first create an ExcelWriter, then write data to it using pandas objects’ to_excel method:

In [71]:
writer = pd.ExcelWriter('examples-20240404/examples/ex2.xlsx')
frame.to_excel(writer, 'Sheet1')
writer.save()

AttributeError: 'OpenpyxlWriter' object has no attribute 'save'

You can also pass a file path to to_excel and avoid the ExcelWriter:

In [67]:
frame.to_excel('examples-20240404/examples/ex2.xlsx')

In [68]:
!rm examples-20240404/examples/ex2.xlsx

'rm' is not recognized as an internal or external command,
operable program or batch file.

## Interacting with Web APIs

Many websites have public APIs providing data feeds via JSON or some other format. There are a number of ways to access these APIs from Python; one easy-to-use method that I recommend is the requests package. To find the last 30 GitHub issues for pandas on GitHub, we can make a GET HTTP request using the add-on requests library.

In [72]:
import requests
url = 'https://api.github.com/repos/pandas-dev/pandas/issues'
resp = requests.get(url)
resp

The Response object’s json method will return a dictionary containing JSON parsed into native Python objects

In [73]:
data = resp.json()
data

[{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/58149',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/58149/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/58149/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/58149/events',
  'html_url': 'https://github.com/pandas-dev/pandas/issues/58149',
  'id': 2225513739,
  'node_id': 'I_kwDOAA0YD86EpqUL',
  'number': 58149,
  'title': 'BUG: Pandas does not recognise older missing value code for double when reading Stata files prior to 108 (Stata 6) format',
  'user': {'login': 'cmjcharlton',
   'id': 90400333,
   'node_id': 'MDQ6VXNlcjkwNDAwMzMz',
   'avatar_url': 'https://avatars.githubusercontent.com/u/90400333?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/cmjcharlton',
   'html_url': 'https://github.com/cmjcharlton',
   'followers_url': 'https://api.github.com/users/cmjcharlton/followers',
   'following_url': 'https://api.github.com/users/cmjcharlton/following{/other_user}',
   'gists_url': 'https://api.github.com/users/cmjcharlton/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/cmjcharlton/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/cmjcharlton/subscriptions',
   'organizations_url': 'https://api.github.com/users/cmjcharlton/orgs',
   'repos_url': 'https://api.github.com/users/cmjcharlton/repos',
   'events_url': 'https://api.github.com/users/cmjcharlton/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/cmjcharlton/received_events',
   'type': 'User',
   'site_admin': False},
  'labels': [{'id': 76811,
    'node_id': 'MDU6TGFiZWw3NjgxMQ==',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug',
    'name': 'Bug',
    'color': 'e10c02',
    'default': False,
    'description': None},
   {'id': 1954720290,
    'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage',
    'name': 'Needs Triage',
    'color': '0052cc',
    'default': False,
    'description': 'Issue that has not been reviewed by a pandas team member'}],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': None,
  'comments': 0,
  'created_at': '2024-04-04T13:24:56Z',
  'updated_at': '2024-04-04T13:24:56Z',
  'closed_at': None,
  'author_association': 'NONE',
  'active_lock_reason': None,
  'body': '### Pandas version checks\n\n- [X] I have checked that this issue has not already been reported.\n\n- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.\n\n- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.\n\n\n### Reproducible Example\n\n```python\n# The problem occurs when reading an external file, so unfortunately this\r\n# requires a data file linked to in the issue description\r\nimport pandas as pd\r\ndf = pd.read_stata("aidsdata.dta")\n```\n\n\n### Issue Description\n\nStata format 108 (corresponding to Stata 6) changed the code used to signify a missing value of type double (from 2^333 [1] to  2^1023 [2]). Pandas does not currently recognise this when reading these Stata file versions and therefore leaves the raw value in the DataFrame (note that the missing code for float types has not changed and therefore this works as expected):\r\n\r\n```python\r\n>>> df = pd.read_stata("aidsdata.dta")\r\n>>> df[[\'gini\', \'urbmf\', \'miltpop\', \'gaplit\']][0:9]\r\n            gini          urbmf    miltpop     gaplit\r\n0   3.900000e-01   1.028946e+00  10.668921  26.999992\r\n1  1.749801e+100  1.749801e+100  13.931355  26.199966\r\n2  1.749801e+100   9.929842e-01   5.936691   0.800000\r\n3  1.749801e+100   9.929842e-01   5.936691   0.800000\r\n4   4.800000e-01  1.749801e+100   6.872657        NaN\r\n5   4.800000e-01  1.749801e+100   6.872657        NaN\r\n6   3.451000e-01   1.550366e+00   5.474547  26.399994\r\n7   3.451000e-01   1.550366e+00   5.474547  26.399994\r\n8   4.700000e-01   9.523810e-01   1.260353        NaN\r\n```\r\n\r\nThe test file used above is \\sg99\\dta\\aidsdata.dta contained in https://web.archive.org/web/19991011204243/http://lib.stat.cmu.edu/stata/STB/stb47v5.zip\r\n\r\nReferences:\r\n[1] Stata 1 reference manual, page 5 (https://www.statalist.org/forums/forum/general-stata-discussion/general/1638352-stata-1-reference-manual-now-available-to-anyone-who-wants-it)\r\n[2] Description of the .dta file format 108, Representation of numbers ([dta_108.txt](https://github.com/pandas-dev/pandas/files/14871718/dta_108.txt))\r\n\n\n### Expected Behavior\n\nI would expect the data displayed to match that in Stata:\r\n```\r\n. dtaversion "aidsdata.dta"\r\n  (file "aidsdata.dta" is .dta-format 105 from Stata 5)\r\n\r\n. use "aidsdata.dta"\r\n(X-cntry data on HIV & Dtrmnts)\r\n\r\n. list gini urbmf miltpop gaplit in 1/10\r\n\r\n     +-------------------------------------+\r\n     |  gini   urbmf    miltpop     gaplit |\r\n     |-------------------------------------|\r\n  1. | 0.390   1.029   10.66892   26.99999 |\r\n  2. |     .       .   13.93135   26.19997 |\r\n  3. |     .   0.993   5.936691   .8000002 |\r\n  4. |     .   0.993   5.936691   .8000002 |\r\n  5. | 0.480       .   6.872657          . |\r\n     |-------------------------------------|\r\n  6. | 0.480       .   6.872657          . |\r\n  7. | 0.345   1.550   5.474547   26.39999 |\r\n  8. | 0.345   1.550   5.474547   26.39999 |\r\n  9. | 0.470   0.952   1.260353          . |\r\n 10. |     .   1.092   2.129809         14 |\r\n     +-------------------------------------+\r\n```\n\n### Installed Versions\n\n<details>\r\n\r\nINSTALLED VERSIONS\r\n------------------\r\ncommit                : bdc79c146c2e32f2cab629be240f01658cfb6cc2\r\npython                : 3.12.2.final.0\r\npython-bits           : 64\r\nOS                    : Windows\r\nOS-release            : 10\r\nVersion               : 10.0.19045\r\nmachine               : AMD64\r\nprocessor             : Intel64 Family 6 Model 158 Stepping 10, GenuineIntel\r\nbyteorder             : little\r\nLC_ALL                : None\r\nLANG                  : None\r\nLOCALE                : English_United Kingdom.1252\r\n\r\npandas                : 2.2.1\r\nnumpy                 : 1.26.4\r\npytz                  : 2024.1\r\ndateutil              : 2.9.0.post0\r\nsetuptools            : 69.2.0\r\npip                   : 24.0\r\nCython                : None\r\npytest                : None\r\nhypothesis            : None\r\nsphinx                : None\r\nblosc                 : None\r\nfeather               : None\r\nxlsxwriter            : None\r\nlxml.etree            : 5.1.0\r\nhtml5lib              : 1.1\r\npymysql               : None\r\npsycopg2              : None\r\njinja2                : None\r\nIPython               : None\r\npandas_datareader     : None\r\nadbc-driver-postgresql: None\r\nadbc-driver-sqlite    : None\r\nbs4                   : 4.12.3\r\nbottleneck            : None\r\ndataframe-api-compat  : None\r\nfastparquet           : None\r\nfsspec                : None\r\ngcsfs                 : None\r\nmatplotlib            : 3.8.3\r\nnumba                 : None\r\nnumexpr               : 2.9.0\r\nodfpy                 : None\r\nopenpyxl              : None\r\npandas_gbq            : None\r\npyarrow               : None\r\npyreadstat            : None\r\npython-calamine       : None\r\npyxlsb                : None\r\ns3fs                  : None\r\nscipy                 : 1.12.0\r\nsqlalchemy            : None\r\ntables                : None\r\ntabulate              : None\r\nxarray                : None\r\nxlrd                  : None\r\nzstandard             : None\r\ntzdata                : 2024.1\r\nqtpy                  : None\r\npyqt5                 : None\r\n\r\n</details>\r\n',
  'reactions': {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/58149/reactions',
   'total_count': 0,
   '+1': 0,
   '-1': 0,
   'laugh': 0,
   'hooray': 0,
   'confused': 0,
   'heart': 0,
   'rocket': 0,
   'eyes': 0},
  'timeline_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/58149/timeline',
  'performed_via_github_app': None,
  'state_reason': None},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/58148',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/58148/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/58148/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/58148/events',
  'html_url': 'https://github.com/pandas-dev/pandas/pull/58148',
  'id': 2225315841,
  'node_id': 'PR_kwDOAA0YD85rsnsy',
  'number': 58148,
  'title': 'BUG: Fix Index.sort_values with natsort_key raises',
  'user': {'login': 'yuanx749',
   'id': 47032563,
   'node_id': 'MDQ6VXNlcjQ3MDMyNTYz',
   'avatar_url': 'https://avatars.githubusercontent.com/u/47032563?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/yuanx749',
   'html_url': 'https://github.com/yuanx749',
   'followers_url': 'https://api.github.com/users/yuanx749/followers',
   'following_url': 'https://api.github.com/users/yuanx749/following{/other_user}',
   'gists_url': 'https://api.github.com/users/yuanx749/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/yuanx749/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/yuanx749/subscriptions',
   'organizations_url': 'https://api.github.com/users/yuanx749/orgs',
   'repos_url': 'https://api.github.com/users/yuanx749/repos',
   'events_url': 'https://api.github.com/users/yuanx749/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/yuanx749/received_events',
   'type': 'User',
   'site_admin': False},
  'labels': [],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': None,
  'comments': 0,
  'created_at': '2024-04-04T12:09:08Z',
  'updated_at': '2024-04-04T13:03:26Z',
  'closed_at': None,
  'author_association': 'CONTRIBUTOR',
  'active_lock_reason': None,
  'draft': False,
  'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/58148',
   'html_url': 'https://github.com/pandas-dev/pandas/pull/58148',
   'diff_url': 'https://github.com/pandas-dev/pandas/pull/58148.diff',
   'patch_url': 'https://github.com/pandas-dev/pandas/pull/58148.patch',
   'merged_at': None},
  'body': '- [x] closes #56081 (Replace xxxx with the GitHub issue number)\r\n- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature\r\n- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).\r\n- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.\r\n- [x] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.\r\n',
  'reactions': {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/58148/reactions',
   'total_count': 0,
   '+1': 0,
   '-1': 0,
   'laugh': 0,
   'hooray': 0,
   'confused': 0,
   'heart': 0,
   'rocket': 0,
   'eyes': 0},
  'timeline_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/58148/timeline',
  'performed_via_github_app': None,
  'state_reason': None},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/58147',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/58147/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/58147/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/58147/events',
  'html_url': 'https://github.com/pandas-dev/pandas/issues/58147',
  'id': 2224855025,
  'node_id': 'I_kwDOAA0YD86EnJfx',
  'number': 58147,
  'title': 'BUG: Casting dtype of large datetime values raises an error inconsistent with resolution',
  'user': {'login': 'amanlai',
   'id': 70603274,
   'node_id': 'MDQ6VXNlcjcwNjAzMjc0',
   'avatar_url': 'https://avatars.githubusercontent.com/u/70603274?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/amanlai',
   'html_url': 'https://github.com/amanlai',
   'followers_url': 'https://api.github.com/users/amanlai/followers',
   'following_url': 'https://api.github.com/users/amanlai/following{/other_user}',
   'gists_url': 'https://api.github.com/users/amanlai/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/amanlai/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/amanlai/subscriptions',
   'organizations_url': 'https://api.github.com/users/amanlai/orgs',
   'repos_url': 'https://api.github.com/users/amanlai/repos',
   'events_url': 'https://api.github.com/users/amanlai/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/amanlai/received_events',
   'type': 'User',
   'site_admin': False},
  'labels': [{'id': 76811,
    'node_id': 'MDU6TGFiZWw3NjgxMQ==',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug',
    'name': 'Bug',
    'color': 'e10c02',
    'default': False,
    'description': None},
   {'id': 1954720290,
    'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage',
    'name': 'Needs Triage',
    'color': '0052cc',
    'default': False,
    'description': 'Issue that has not been reviewed by a pandas team member'}],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': None,
  'comments': 1,
  'created_at': '2024-04-04T08:35:19Z',
  'updated_at': '2024-04-04T10:01:19Z',
  'closed_at': None,
  'author_association': 'NONE',
  'active_lock_reason': None,
  'body': '### Pandas version checks\n\n- [X] I have checked that this issue has not already been reported.\n\n- [x] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.\n\n- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.\n\n\n### Reproducible Example\n\n```python\nimport pandas as pd\r\nfrom datetime import datetime, UTC\r\nlst = [datetime(3000,1,1, tzinfo=UTC), datetime(939,12,31, tzinfo=UTC)]\r\ns = pd.Series(lst, dtype=\'datetime64[s]\')\r\n```\n```\n\n\n### Issue Description\n\nThe above code raises the following error:\r\n```none\r\nTraceback (most recent call last):\r\n  File "<pyshell#75>", line 1, in <module>\r\n    pd.Series(lst, dtype=\'datetime64[ns]\')\r\n  File "C:\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\series.py", line 512, in __init__\r\n    data = sanitize_array(data, index, dtype, copy)\r\n  File "C:\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\construction.py", line 628, in sanitize_array\r\n    subarr = _try_cast(data, dtype, copy)\r\n  File "C:\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\construction.py", line 785, in _try_cast\r\n    return maybe_cast_to_datetime(arr, dtype)\r\n  File "C:\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\dtypes\\cast.py", line 1216, in maybe_cast_to_datetime\r\n    dta = DatetimeArray._from_sequence(value, dtype=dtype)\r\n  File "C:\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\arrays\\datetimes.py", line 297, in _from_sequence\r\n    return cls._from_sequence_not_strict(scalars, dtype=dtype, copy=copy)\r\n  File "C:\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\arrays\\datetimes.py", line 339, in _from_sequence_not_strict\r\n    subarr, tz, inferred_freq = _sequence_to_dt64ns(\r\n  File "C:\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\arrays\\datetimes.py", line 2226, in _sequence_to_dt64ns\r\n    data, inferred_tz = objects_to_datetime64ns(\r\n  File "C:\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\arrays\\datetimes.py", line 2346, in objects_to_datetime64ns\r\n    result, tz_parsed = tslib.array_to_datetime(\r\n  File "tslib.pyx", line 403, in pandas._libs.tslib.array_to_datetime\r\n  File "tslib.pyx", line 552, in pandas._libs.tslib.array_to_datetime\r\n  File "tslib.pyx", line 487, in pandas._libs.tslib.array_to_datetime\r\n  File "conversion.pyx", line 767, in pandas._libs.tslibs.conversion.parse_pydatetime\r\n  File "np_datetime.pyx", line 231, in pandas._libs.tslibs.np_datetime.check_dts_bounds\r\npandas._libs.tslibs.np_datetime.OutOfBoundsDatetime: Out of bounds nanosecond timestamp: 3000-01-01 00:00:00, at position 0\r\n```\r\nThe above code attempts to cast to `datetime[s]`, not `datetime[ns]`, so the error seems inconsistent.\r\n\r\nWeirdly, if I cast each datetime into a POSIX timestamp and try again, the casting works without errors.\r\n```python\r\nlst1 = [x.timestamp() for x in lst]\r\ns = pd.Series(lst1, dtype=\'datetime64[s]\')    # <--- OK\r\n```\n\n### Expected Behavior\n\nSince the POSIX timestamp casting works fine, the expected behavior is the produce the following output:\r\n```none\r\n0   3000-01-01\r\n1    939-12-31\r\ndtype: datetime64[s]\r\n```\r\n\r\nAt the minimum, the error message should not say `Out of bounds nanosecond timestamp: ` because the casting resolution is not nanosecond.\n\n### Installed Versions\n\n<details>\r\n\r\nPython 3.12.0\r\npandas==2.1.1\r\nnumpy==1.26.0\r\nWindows 10 64-bit\r\n</details>\r\n',
  'reactions': {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/58147/reactions',
   'total_count': 0,
   '+1': 0,
   '-1': 0,
   'laugh': 0,
   'hooray': 0,
   'confused': 0,
   'heart': 0,
   'rocket': 0,
   'eyes': 0},
  'timeline_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/58147/timeline',
  'performed_via_github_app': None,
  'state_reason': None},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/58146',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/58146/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/58146/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/58146/events',
  'html_url': 'https://github.com/pandas-dev/pandas/issues/58146',
  'id': 2224684599,
  'node_id': 'I_kwDOAA0YD86Emf43',
  'number': 58146,
  'title': 'BUG: incorrect aggregation of dataframe when using UDF with kwarg',
  'user': {'login': 'nicholas-ys-tan',
   'id': 39729063,
   'node_id': 'MDQ6VXNlcjM5NzI5MDYz',
   'avatar_url': 'https://avatars.githubusercontent.com/u/39729063?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/nicholas-ys-tan',
   'html_url': 'https://github.com/nicholas-ys-tan',
   'followers_url': 'https://api.github.com/users/nicholas-ys-tan/followers',
   'following_url': 'https://api.github.com/users/nicholas-ys-tan/following{/other_user}',
   'gists_url': 'https://api.github.com/users/nicholas-ys-tan/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/nicholas-ys-tan/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/nicholas-ys-tan/subscriptions',
   'organizations_url': 'https://api.github.com/users/nicholas-ys-tan/orgs',
   'repos_url': 'https://api.github.com/users/nicholas-ys-tan/repos',
   'events_url': 'https://api.github.com/users/nicholas-ys-tan/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/nicholas-ys-tan/received_events',
   'type': 'User',
   'site_admin': False},
  'labels': [{'id': 76811,

In [74]:
data[0]['url']

'https://api.github.com/repos/pandas-dev/pandas/issues/58149'

Each element in data is a dictionary containing all of the data found on a GitHub issue page (except for the comments). We can pass data directly to DataFrame and extract fields of interest:

In [75]:
issues = pd.DataFrame(data, columns=['number', 'title',
                                     'labels', 'state'])
issues

,number,title,labels,state
0,58149,BUG: Pandas does not recognise older missing v...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
1,58148,BUG: Fix Index.sort_values with natsort_key ra...,[],open
2,58147,BUG: Casting dtype of large datetime values ra...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
3,58146,BUG: incorrect aggregation of dataframe when u...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
4,58145,REGR: from_records not initializing subclasses...,"[{'id': 32815646, 'node_id': 'MDU6TGFiZWwzMjgx...",open
5,58143,REF: Allow Index._with_infer to also return Ra...,"[{'id': 1218227310, 'node_id': 'MDU6TGFiZWwxMj...",open
6,58142,QST: loc returns matrix with one row when ind...,"[{'id': 34444536, 'node_id': 'MDU6TGFiZWwzNDQ0...",open
7,58141,ENH: Consistent naming conventions for string ...,"[{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg=...",open
8,58139,BUG: fixed to_numeric loss in precision when c...,[],open
9,58136,ENH: Processing of .mask() for pd.NA #56844,"[{'id': 2822342, 'node_id': 'MDU6TGFiZWwyODIyM...",open
10,58134,BUILD: Unable to install pandas on 32bit pytho...,"[{'id': 129350, 'node_id': 'MDU6TGFiZWwxMjkzNT...",open
11,58133,BUG: pandas groupby returns different results ...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
12,58132,API: add numeric_only support to groupby agg,[],open
13,58131,BUG: read_csv file handle not closed after error,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
14,58130,BUG: Integers with extreme values are incorrec...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
15,58129,Convert result of group by agg to pyarrow if i...,"[{'id': 697792067, 'node_id': 'MDU6TGFiZWw2OTc...",open
16,58128,"When excel cell with 0x005F_FFFF, pandas read ...","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
17,58125,CLN: enforce deprecation of the `kind` keyword...,[],open
18,58124,BUG: Inconsistent `RollingGroupby` Behaviour,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
19,58123,ENH: adding jsonline output format,"[{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg=...",open
20,58122,DEPR: keyword-only arguments for DataFrame/Ser...,"[{'id': 87485152, 'node_id': 'MDU6TGFiZWw4NzQ4...",open
21,58121,BUG: Timestamp.unit now reflects changes in co...,"[{'id': 3713792788, 'node_id': 'LA_kwDOAA0YD87...",open
22,58120,BUG: to_datetime timestamp parsing in 2.x,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
23,58117,PERF: groupby returns a RangeIndex from groups...,"[{'id': 233160, 'node_id': 'MDU6TGFiZWwyMzMxNj...",open
24,58116,BUG: Setting values on `DataFrame` with multi-...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
25,58115,DOC: Remove deprecated methods from code_check...,"[{'id': 106935113, 'node_id': 'MDU6TGFiZWwxMDY...",open
26,58113,ENH: function to concatenate columns with a se...,"[{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg=...",open
27,58110,DEPR: rename `startingMonth` to `starting_mont...,[],open
28,58108,ENH: Series.map() that works with a dictionary...,"[{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg=...",open
29,58105,Backport PR #58087 on branch 2.2.x (BLD: Build...,"[{'id': 129350, 'node_id': 'MDU6TGFiZWwxMjkzNT...",open

With a bit of elbow grease, you can create some higher-level interfaces to common web APIs that return DataFrame objects for easy analysis.

### YAHOO FINANCE

In [76]:
import sys
!conda install --yes --prefix {sys.prefix} -c conda-forge yfinance
#!{sys.executable} -m pip install openpyxl

Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... done

# All requested packages already installed.

==> WARNING: A newer version of conda exists. <==
  current version: 23.7.4
  latest version: 24.3.0

Please update conda by running

    $ conda update -n base -c defaults conda

Or to minimize the number of packages updated during conda update use

     conda install conda=24.3.0

In [77]:
conda list

# packages in environment at C:\Users\karol\anaconda3:
#
# Name                    Version                   Build  Channel
_anaconda_depends         2023.09             py311_mkl_1
abseil-cpp                20211102.0           hd77b12b_0
aiobotocore               2.5.0           py311haa95532_0
aiofiles                  22.1.0          py311haa95532_0
aiohttp                   3.8.5           py311h2bbff1b_0
aioitertools              0.7.1              pyhd3eb1b0_0
aiosignal                 1.2.0              pyhd3eb1b0_0
aiosqlite                 0.18.0          py311haa95532_0
alabaster                 0.7.12             pyhd3eb1b0_0
anaconda-anon-usage       0.4.2           py311hfc23b7f_0
anaconda-catalogs         0.2.0           py311haa95532_0
anaconda-client           1.12.1          py311haa95532_0
anaconda-cloud-auth       0.1.3           py311haa95532_0
anaconda-navigator        2.5.0           py311haa95532_0
anaconda-project          0.11.1          py311haa95532_0
anyio                     3.5.0           py311haa95532_0
aom                       3.6.0                hd77b12b_0
appdirs                   1.4.4              pyhd3eb1b0_0
argon2-cffi               21.3.0             pyhd3eb1b0_0
argon2-cffi-bindings      21.2.0          py311h2bbff1b_0
arrow                     1.2.3           py311haa95532_1
arrow-cpp                 11.0.0               ha81ea56_2
astroid                   2.14.2          py311haa95532_0
astropy                   5.1             py311h5bb9823_0
asttokens                 2.0.5              pyhd3eb1b0_0
async-timeout             4.0.2           py311haa95532_0
atomicwrites              1.4.0                      py_0
attrs                     22.1.0          py311haa95532_0
automat                   20.2.0                     py_0
autopep8                  1.6.0              pyhd3eb1b0_1
aws-c-common              0.6.8                h2bbff1b_1
aws-c-event-stream        0.1.6                hd77b12b_6
aws-checksums             0.1.11               h2bbff1b_2
aws-sdk-cpp               1.8.185              hd77b12b_1
babel                     2.11.0          py311haa95532_0
backcall                  0.2.0              pyhd3eb1b0_0
backports                 1.1                pyhd3eb1b0_0
backports.functools_lru_cache 1.6.4              pyhd3eb1b0_0
backports.tempfile        1.0                pyhd3eb1b0_1
backports.weakref         1.0.post1                  py_1
bcrypt                    3.2.0           py311h2bbff1b_1
beautifulsoup4            4.12.2          py311haa95532_0
binaryornot               0.4.4              pyhd3eb1b0_1
black                     23.3.0          py311haa95532_0
blas                      1.0                         mkl
bleach                    4.1.0              pyhd3eb1b0_0
blosc                     1.21.3               h6c2663c_0
bokeh                     3.2.1           py311h746a85d_0
boltons                   23.0.0          py311haa95532_0
boost-cpp                 1.82.0               h59b6b97_1
botocore                  1.29.76         py311haa95532_0
bottleneck                1.3.5           py311h5bb9823_0
brotli                    1.0.9                h2bbff1b_7
brotli-bin                1.0.9                h2bbff1b_7
brotlipy                  0.7.0           py311h2bbff1b_1002
bzip2                     1.0.8                he774522_0
c-ares                    1.19.1               h2bbff1b_0
c-blosc2                  2.8.0                hd77b12b_0
ca-certificates           2024.2.2             h56e8100_0    conda-forge
certifi                   2024.2.2           pyhd8ed1ab_0    conda-forge
cffi                      1.15.1          py311h2bbff1b_3
cfitsio                   3.470                h2bbff1b_7
chardet                   4.0.0           py311haa95532_1003
charls                    2.2.0                h6c2663c_0
charset-normalizer        2.0.4              pyhd3eb1b0_0
click                     8.0.4           py311haa95532_0
cloudpickle               2.2.1           py311haa95532_0
clyent                    1.2.2           py311haa95532_1
colorama                  0.4.6           py311haa95532_0
colorcet                  3.0.1           py311haa95532_0
comm                      0.1.2           py311haa95532_0
conda                     23.7.4          py311haa95532_0
conda-build               3.26.1          py311haa95532_0
conda-content-trust       0.2.0           py311haa95532_0
conda-index               0.3.0           py311haa95532_0
conda-libmamba-solver     23.7.0          py311haa95532_0
conda-pack                0.6.0              pyhd3eb1b0_0
conda-package-handling    2.2.0           py311haa95532_0
conda-package-streaming   0.9.0           py311haa95532_0
conda-repo-cli            1.0.75          py311haa95532_0
conda-token               0.4.0              pyhd3eb1b0_0
conda-verify              3.4.2                      py_1
console_shortcut          0.1.1                         4
constantly                15.1.0          py311haa95532_0
contourpy                 1.0.5           py311h59b6b97_0
cookiecutter              1.7.3              pyhd3eb1b0_0
cryptography              41.0.3          py311h89fc84f_0
cssselect                 1.1.0              pyhd3eb1b0_0
curl                      8.1.1                h2bbff1b_0
cycler                    0.11.0             pyhd3eb1b0_0
cytoolz                   0.12.0          py311h2bbff1b_0
daal4py                   2023.1.1        py311h30df693_0
dal                       2023.1.1         h59b6b97_48681
dask                      2023.6.0        py311haa95532_0
dask-core                 2023.6.0        py311haa95532_0
datasets                  2.12.0          py311haa95532_0
datashader                0.15.2          py311haa95532_0
datashape                 0.5.4           py311haa95532_1
dav1d                     1.2.1                h2bbff1b_0
debugpy                   1.6.7           py311hd77b12b_0
decorator                 5.1.1              pyhd3eb1b0_0
defusedxml                0.7.1              pyhd3eb1b0_0
diff-match-patch          20200713           pyhd3eb1b0_0
dill                      0.3.6           py311haa95532_0
distributed               2023.6.0        py311haa95532_0
docstring-to-markdown     0.11            py311haa95532_0
docutils                  0.18.1          py311haa95532_3
entrypoints               0.4             py311haa95532_0
et_xmlfile                1.1.0           py311haa95532_0
executing                 0.8.3              pyhd3eb1b0_0
filelock                  3.9.0           py311haa95532_0
flake8                    6.0.0           py311haa95532_0
flask                     2.2.2           py311haa95532_0
fmt                       9.1.0                h6d14046_0
fonttools                 4.25.0             pyhd3eb1b0_0
freetype                  2.12.1               ha860e81_0
frozendict                2.4.1           py311ha68e1ae_0    conda-forge
frozenlist                1.3.3           py311h2bbff1b_0
fsspec                    2023.4.0        py311haa95532_0
future                    0.18.3          py311haa95532_0
gensim                    4.3.0           py311heda8569_0
gflags                    2.2.2                ha925a31_0
giflib                    5.2.1                h8cc25b3_3
glib                      2.69.1               h5dc1a3c_2
glob2                     0.7                pyhd3eb1b0_0
glog                      0.5.0                hd77b12b_0
greenlet                  2.0.1           py311hd77b12b_0
grpc-cpp                  1.48.2               hfe90ff0_1
h5py                      3.9.0           py311h4e0e482_0
hdf5                      1.12.1               h51c971a_3
heapdict                  1.0.1              pyhd3eb1b0_0
holoviews                 1.17.1          py311haa95532_0
html5lib                  1.1                pyh9f0ad1d_0    conda-forge
huggingface_hub           0.15.1          py311haa95532_0
hvplot                    0.8.4           py311haa95532_0
hyperlink                 21.0.0             pyhd3eb1b0_0
icc_rt                    2022.1.0             h6049295_2
icu                       58.2                 ha925a31_3
idna                      3.4             py311haa95532_0
imagecodecs               2023.1.23       py311he6ff3c7_0
imageio                   2.26.0          py311haa95532_0
imagesize                 1.4.1           py311haa95532_0
imbalanced-learn          0.10.1          py311haa95532_1
importlib-metadata        6.0.0           py311haa95532_0
importlib_metadata        6.0.0                hd3eb1b0_0
incremental               21.3.0             pyhd3eb1b0_0
inflection                0.5.1           py311haa95532_0
iniconfig                 1.1.1              pyhd3eb1b0_0
intake                    0.6.8           py311haa95532_0
intel-openmp              2023.1.0         h59b6b97_46319
intervaltree              3.1.0              pyhd3eb1b0_0
ipykernel                 6.25.0          py311h746a85d_0
ipython                   8.15.0          py311haa95532_0
ipython_genutils          0.2.0              pyhd3eb1b0_1
ipywidgets                8.0.4           py311haa95532_0
isort                     5.9.3              pyhd3eb1b0_0
itemadapter               0.3.0              pyhd3eb1b0_0
itemloaders               1.0.4              pyhd3eb1b0_1
itsdangerous              2.0.1              pyhd3eb1b0_0
jaraco.classes            3.2.1              pyhd3eb1b0_0
jedi                      0.18.1          py311haa95532_1
jellyfish                 1.0.1           py311h36a85e1_0
jinja2                    3.1.2           py311haa95532_0
jinja2-time               0.2.0              pyhd3eb1b0_3
jmespath                  0.10.0             pyhd3eb1b0_0
joblib                    1.2.0           py311haa95532_0
jpeg                      9e                   h2bbff1b_1
jq                        1.6                  haa95532_1
json5                     0.9.6              pyhd3eb1b0_0
jsonpatch                 1.32               pyhd3eb1b0_0
jsonpointer               2.1                pyhd3eb1b0_0
jsonschema                4.17.3          py311haa95532_0
jupyter                   1.0.0           py311haa95532_8
jupyter_client            7.4.9           py311haa95532_0
jupyter_console           6.6.3           py311haa95532_0
jupyter_core              5.3.0           py311haa95532_0
jupyter_events            0.6.3           py311haa95532_0
jupyter_server            1.23.4          py311haa95532_0
jupyter_server_fileid     0.9.0           py311haa95532_0
jupyter_server_ydoc       0.8.0           py311haa95532_1
jupyter_ydoc              0.2.4           py311haa95532_0
jupyterlab                3.6.3           py311haa95532_0
jupyterlab_pygments       0.1.2                      py_0
jupyterlab_server         2.22.0          py311haa95532_0
jupyterlab_widgets        3.0.5           py311haa95532_0
jupyterthemes             0.20.0                   pypi_0    pypi
kaleido-core              0.2.1                h2bbff1b_0
keyring                   23.13.1         py311haa95532_0
kiwisolver                1.4.4           py311hd77b12b_0
krb5                      1.20.1               h5b6d351_0
lazy-object-proxy         1.6.0           py311h2bbff1b_0
lazy_loader               0.2             py311haa95532_0
lcms2                     2.12                 h83e58a3_0
lerc                      3.0                  hd77b12b_0
lesscpy                   0.15.1                   pypi_0    pypi
libaec                    1.0.4                h33f27b4_1
libarchive                3.6.2                hb62f4d4_2
libavif                   0.11.1               h2bbff1b_0
libboost                  1.82.0               hae598e9_1
libbrotlicommon           1.0.9                h2bbff1b_7
libbrotlidec              1.0.9                h2bbff1b_7
libbrotlienc              1.0.9                h2bbff1b_7
libclang                  14.0.6          default_hb5a9fac_1
libclang13                14.0.6          default_h8e68704_1
libcurl                   8.1.1                h86230a5_0
libdeflate                1.17                 h2bbff1b_0
libevent                  2.1.12               h56d1f94_1
libffi                    3.4.4                hd77b12b_0
libiconv                  1.16                 h2bbff1b_2
liblief                   0.12.3               hd77b12b_0
libmamba                  1.5.1                hcd6fe79_0
libmambapy                1.5.1           py311h77c03ed_0
libpng                    1.6.39               h8cc25b3_0
libpq                     12.15                h906ac69_1
libprotobuf               3.20.3               h23ce68f_0
libsodium                 1.0.18               h62dcd97_0
libsolv                   0.7.24               h23ce68f_0
libspatialindex           1.9.3                h6c2663c_0
libsqlite                 3.45.2               hcfcfb64_0    conda-forge
libssh2                   1.10.0               he2ea4bf_2
libthrift                 0.15.0               h4364b78_2
libtiff                   4.5.1                hd77b12b_0
libwebp                   1.3.2                hbc33d0d_0
libwebp-base              1.3.2                h2bbff1b_0
libxml2                   2.10.4               h0ad7f3c_1
libxslt                   1.1.37               h2bbff1b_1
libzopfli                 1.0.3                ha925a31_0
linkify-it-py             2.0.0           py311haa95532_0
llvmlite                  0.40.0          py311hf2fb9eb_0
locket                    1.0.0           py311haa95532_0
lxml                      4.9.3           py311h09808a7_0
lz4                       4.3.2           py311h2bbff1b_0
lz4-c                     1.9.4                h2bbff1b_0
lzo                       2.10                 he774522_2
m2-msys2-runtime          2.5.0.17080.65c939c               3
m2-patch                  2.7.5                         2
m2w64-libwinpthread-git   5.0.0.4634.697f757               2
markdown                  3.4.1           py311haa95532_0
markdown-it-py            2.2.0           py311haa95532_1
markupsafe                2.1.1           py311h2bbff1b_0
mathjax                   2.7.5                haa95532_0
matplotlib                3.7.2           py311haa95532_0
matplotlib-base           3.7.2           py311hf62ec03_0
matplotlib-inline         0.1.6           py311haa95532_0
mccabe                    0.7.0              pyhd3eb1b0_0
mdit-py-plugins           0.3.0           py311haa95532_0
mdurl                     0.1.0           py311haa95532_0
menuinst                  1.4.19          py311h59b6b97_1
mistune                   0.8.4           py311h2bbff1b_1000
mkl                       2023.1.0         h6b88ed4_46357
mkl-service               2.4.0           py311h2bbff1b_1
mkl_fft                   1.3.8           py311h2bbff1b_0
mkl_random                1.2.4           py311h59b6b97_0
more-itertools            8.12.0             pyhd3eb1b0_0
mpmath                    1.3.0           py311haa95532_0
msgpack-python            1.0.3           py311h59b6b97_0
msys2-conda-epoch         20160418                      1
multidict                 6.0.2           py311h2bbff1b_0
multipledispatch          0.6.0           py311haa95532_0
multiprocess              0.70.14         py311haa95532_0
multitasking              0.0.9              pyhd8ed1ab_0    conda-forge
munkres                   1.1.4                      py_0
mypy_extensions           1.0.0           py311haa95532_0
navigator-updater         0.4.0           py311haa95532_1
nbclassic                 0.5.5           py311haa95532_0
nbclient                  0.5.13          py311haa95532_0
nbconvert                 6.5.4           py311haa95532_0
nbformat                  5.9.2           py311haa95532_0
nest-asyncio              1.5.6           py311haa95532_0
networkx                  3.1             py311haa95532_0
nltk                      3.8.1           py311haa95532_0
notebook                  6.5.4           py311haa95532_1
notebook-shim             0.2.2           py311haa95532_0
numba                     0.57.1          py311hf62ec03_0
numexpr                   2.8.4           py311h1fcbade_1
numpy                     1.24.3          py311hdab7c0b_1
numpy-base                1.24.3          py311hd01c5d8_1
numpydoc                  1.5.0           py311haa95532_0
openjpeg                  2.4.0                h4fc8c34_0
openpyxl                  3.0.10          py311h2bbff1b_0
openssl                   3.2.1                hcfcfb64_1    conda-forge
orc                       1.7.4                h623e30f_1
packaging                 23.1            py311haa95532_0
pandas                    2.0.3           py311hf62ec03_0
pandas-datareader         0.10.0                   pypi_0    pypi
pandocfilters             1.5.0              pyhd3eb1b0_0
panel                     1.2.3           py311haa95532_0
param                     1.13.0          py311haa95532_0
paramiko                  2.8.1              pyhd3eb1b0_0
parsel                    1.6.0           py311haa95532_0
parso                     0.8.3              pyhd3eb1b0_0
partd                     1.4.0           py311haa95532_0
pathlib                   1.0.1              pyhd3eb1b0_1
pathspec                  0.10.3          py311haa95532_0
patsy                     0.5.3           py311haa95532_0
pcre                      8.45                 hd77b12b_0
pcre2                     10.42                h0ff8eda_0
peewee                    3.17.1          py311had142b2_0    conda-forge
pep8                      1.7.1           py311haa95532_1
pexpect                   4.8.0              pyhd3eb1b0_3
pickleshare               0.7.5           pyhd3eb1b0_1003
pillow                    9.4.0           py311hd77b12b_1
pip                       23.3.1          py311haa95532_0
pkce                      1.0.3           py311haa95532_0
pkginfo                   1.9.6           py311haa95532_0
platformdirs              3.10.0          py311haa95532_0
plotly                    5.9.0           py311haa95532_0
pluggy                    1.0.0           py311haa95532_1
ply                       3.11            py311haa95532_0
powershell_shortcut       0.0.1                         3
poyo                      0.5.0              pyhd3eb1b0_0
prometheus_client         0.14.1          py311haa95532_0
prompt-toolkit            3.0.36          py311haa95532_0
prompt_toolkit            3.0.36               hd3eb1b0_0
protego                   0.1.16                     py_0
psutil                    5.9.0           py311h2bbff1b_0
ptyprocess                0.7.0              pyhd3eb1b0_2
pure_eval                 0.2.2              pyhd3eb1b0_0
py-cpuinfo                8.0.0              pyhd3eb1b0_1
py-lief                   0.12.3          py311hd77b12b_0
pyarrow                   11.0.0          py311h8a3a540_1
pyasn1                    0.4.8              pyhd3eb1b0_0
pyasn1-modules            0.2.8                      py_0
pybind11-abi              4                    hd3eb1b0_1
pycodestyle               2.10.0          py311haa95532_0
pycosat                   0.6.4           py311h2bbff1b_0
pycparser                 2.21               pyhd3eb1b0_0
pyct                      0.5.0           py311haa95532_0
pycurl                    7.45.2          py311he2ea4bf_1
pydantic                  1.10.8          py311h2bbff1b_0
pydispatcher              2.0.5           py311haa95532_2
pydocstyle                6.3.0           py311haa95532_0
pyerfa                    2.0.0           py311h2bbff1b_0
pyflakes                  3.0.1           py311haa95532_0
pygments                  2.15.1          py311haa95532_1
pyjwt                     2.4.0           py311haa95532_0
pylint                    2.16.2          py311haa95532_0
pylint-venv               2.3.0           py311haa95532_0
pyls-spyder               0.4.0              pyhd3eb1b0_0

In [78]:
import yfinance as yf
msft = yf.Ticker("MSFT")
print(msft)

yfinance.Ticker object <MSFT>

In [79]:
msft.info

{'address1': 'One Microsoft Way',
 'city': 'Redmond',
 'state': 'WA',
 'zip': '98052-6399',
 'country': 'United States',
 'phone': '425 882 8080',
 'website': 'https://www.microsoft.com',
 'industry': 'Software - Infrastructure',
 'industryKey': 'software-infrastructure',
 'industryDisp': 'Software - Infrastructure',
 'sector': 'Technology',
 'sectorKey': 'technology',
 'sectorDisp': 'Technology',
 'longBusinessSummary': 'Microsoft Corporation develops and supports software, services, devices and solutions worldwide. The Productivity and Business Processes segment offers office, exchange, SharePoint, Microsoft Teams, office 365 Security and Compliance, Microsoft viva, and Microsoft 365 copilot; and office consumer services, such as Microsoft 365 consumer subscriptions, Office licensed on-premises, and other office services. This segment also provides LinkedIn; and dynamics business solutions, including Dynamics 365, a set of intelligent, cloud-based applications across ERP, CRM, power apps, and power automate; and on-premises ERP and CRM applications. The Intelligent Cloud segment offers server products and cloud services, such as azure and other cloud services; SQL and windows server, visual studio, system center, and related client access licenses, as well as nuance and GitHub; and enterprise services including enterprise support services, industry solutions, and nuance professional services. The More Personal Computing segment offers Windows, including windows OEM licensing and other non-volume licensing of the Windows operating system; Windows commercial comprising volume licensing of the Windows operating system, windows cloud services, and other Windows commercial offerings; patent licensing; and windows Internet of Things; and devices, such as surface, HoloLens, and PC accessories. Additionally, this segment provides gaming, which includes Xbox hardware and content, and first- and third-party content; Xbox game pass and other subscriptions, cloud gaming, advertising, third-party disc royalties, and other cloud services; and search and news advertising, which includes Bing, Microsoft News and Edge, and third-party affiliates. The company sells its products through OEMs, distributors, and resellers; and directly through digital marketplaces, online, and retail stores. The company was founded in 1975 and is headquartered in Redmond, Washington.',
 'fullTimeEmployees': 221000,
 'companyOfficers': [{'maxAge': 1,
   'name': 'Mr. Satya  Nadella',
   'age': 56,
   'title': 'Chairman & CEO',
   'yearBorn': 1967,
   'fiscalYear': 2023,
   'totalPay': 9276400,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Bradford L. Smith LCA',
   'age': 64,
   'title': 'President & Vice Chairman',
   'yearBorn': 1959,
   'fiscalYear': 2023,
   'totalPay': 3591277,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Amy E. Hood',
   'age': 51,
   'title': 'Executive VP & CFO',
   'yearBorn': 1972,
   'fiscalYear': 2023,
   'totalPay': 3452196,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Judson B. Althoff',
   'age': 49,
   'title': 'Executive VP & Chief Commercial Officer',
   'yearBorn': 1974,
   'fiscalYear': 2023,
   'totalPay': 3355797,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Christopher David Young',
   'age': 51,
   'title': 'Executive Vice President of Business Development, Strategy & Ventures',
   'yearBorn': 1972,
   'fiscalYear': 2023,
   'totalPay': 2460507,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Alice L. Jolla',
   'age': 56,
   'title': 'Corporate VP & Chief Accounting Officer',
   'yearBorn': 1967,
   'fiscalYear': 2023,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. James Kevin Scott',
   'age': 51,
   'title': 'Executive VP of AI & CTO',
   'yearBorn': 1972,
   'fiscalYear': 2023,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Brett  Iversen',
   'title': 'Vice President of Investor Relations',
   'fiscalYear': 2023,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Hossein  Nowbar',
   'title': 'Chief Legal Officer',
   'fiscalYear': 2023,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Frank X. Shaw',
   'title': 'Chief Communications Officer',
   'fiscalYear': 2023,
   'exercisedValue': 0,
   'unexercisedValue': 0}],
 'auditRisk': 2,
 'boardRisk': 5,
 'compensationRisk': 2,
 'shareHolderRightsRisk': 2,
 'overallRisk': 1,
 'governanceEpochDate': 1711929600,
 'compensationAsOfEpochDate': 1703980800,
 'irWebsite': 'http://www.microsoft.com/investor/default.aspx',
 'maxAge': 86400,
 'priceHint': 2,
 'previousClose': 420.45,
 'open': 419.73,
 'dayLow': 423.32,
 'dayHigh': 427.58,
 'regularMarketPreviousClose': 420.45,
 'regularMarketOpen': 419.73,
 'regularMarketDayLow': 423.32,
 'regularMarketDayHigh': 427.58,
 'dividendRate': 3.0,
 'dividendYield': 0.0070999996,
 'exDividendDate': 1715731200,
 'payoutRatio': 0.2523,
 'fiveYearAvgDividendYield': 0.95,
 'beta': 0.877,
 'trailingPE': 38.683758,
 'forwardPE': 31.884443,
 'volume': 2741152,
 'regularMarketVolume': 2741152,
 'averageVolume': 22593185,
 'averageVolume10days': 17843910,
 'averageDailyVolume10Day': 17843910,
 'bid': 426.0,
 'ask': 426.6,
 'bidSize': 200,
 'askSize': 200,
 'marketCap': 3167559614464,
 'fiftyTwoWeekLow': 275.37,
 'fiftyTwoWeekHigh': 430.82,
 'priceToSalesTrailing12Months': 13.918262,
 'fiftyDayAverage': 412.6328,
 'twoHundredDayAverage': 364.4304,
 'trailingAnnualDividendRate': 2.86,
 'trailingAnnualDividendYield': 0.0068022353,
 'currency': 'USD',
 'enterpriseValue': 3154503008256,
 'profitMargins': 0.36269,
 'floatShares': 7418919053,
 'sharesOutstanding': 7430439936,
 'sharesShort': 54210656,
 'sharesShortPriorMonth': 42451775,
 'sharesShortPreviousMonthDate': 1707955200,
 'dateShortInterest': 1710460800,
 'sharesPercentSharesOut': 0.0073,
 'heldPercentInsiders': 0.00054000004,
 'heldPercentInstitutions': 0.73844004,
 'shortRatio': 2.46,
 'shortPercentOfFloat': 0.0073,
 'impliedSharesOutstanding': 7447220224,
 'bookValue': 32.06,
 'priceToBook': 13.296787,
 'lastFiscalYearEnd': 1688083200,
 'nextFiscalYearEnd': 1719705600,
 'mostRecentQuarter': 1703980800,
 'earningsQuarterlyGrowth': 0.332,
 'netIncomeToCommon': 82541002752,
 'trailingEps': 11.02,
 'forwardEps': 13.37,
 'pegRatio': 2.21,
 'lastSplitFactor': '2:1',
 'lastSplitDate': 1045526400,
 'enterpriseToRevenue': 13.861,
 'enterpriseToEbitda': 26.637,
 '52WeekChange': 0.44200957,
 'SandP52WeekChange': 0.26954067,
 'lastDividendValue': 0.75,
 'lastDividendDate': 1707868800,
 'exchange': 'NMS',
 'quoteType': 'EQUITY',
 'symbol': 'MSFT',
 'underlyingSymbol': 'MSFT',
 'shortName': 'Microsoft Corporation',
 'longName': 'Microsoft Corporation',
 'firstTradeDateEpochUtc': 511108200,
 'timeZoneFullName': 'America/New_York',
 'timeZoneShortName': 'EDT',
 'uuid': 'b004b3ec-de24-385e-b2c1-923f10d3fb62',
 'messageBoardId': 'finmb_21835',
 'gmtOffSetMilliseconds': -14400000,
 'currentPrice': 426.295,
 'targetHighPrice': 550.0,
 'targetLowPrice': 298.1,
 'targetMeanPrice': 460.92,
 'targetMedianPrice': 462.0,
 'recommendationMean': 1.7,
 'recommendationKey': 'buy',
 'numberOfAnalystOpinions': 48,
 'totalCash': 80981999616,
 'totalCashPerShare': 10.899,
 'ebitda': 118427000832,
 'totalDebt': 111358001152,
 'quickRatio': 1.096,
 'currentRatio': 1.218,
 'totalRevenue': 227583000576,
 'debtToEquity': 46.736,
 'revenuePerShare': 30.612,
 'returnOnAssets': 0.1519,
 'returnOnEquity': 0.39174,
 'freeCashflow': 58680999936,
 'operatingCashflow': 102646996992,
 'earningsGrowth': 0.332,
 'revenueGrowth': 0.176,
 'grossMargins': 0.69815004,
 'ebitdaMargins': 0.52037,
 'operatingMargins': 0.43585998,
 'financialCurrency': 'USD',
 'trailingPegRatio': 2.1374}

In [80]:
msft.dividends

Date
2003-02-19 00:00:00-05:00    0.08
2003-10-15 00:00:00-04:00    0.16
2004-08-23 00:00:00-04:00    0.08
2004-11-15 00:00:00-05:00    3.08
2005-02-15 00:00:00-05:00    0.08
2005-05-16 00:00:00-04:00    0.08
2005-08-15 00:00:00-04:00    0.08
2005-11-15 00:00:00-05:00    0.08
2006-02-15 00:00:00-05:00    0.09
2006-05-15 00:00:00-04:00    0.09
2006-08-15 00:00:00-04:00    0.09
2006-11-14 00:00:00-05:00    0.10
2007-02-13 00:00:00-05:00    0.10
2007-05-15 00:00:00-04:00    0.10
2007-08-14 00:00:00-04:00    0.10
2007-11-13 00:00:00-05:00    0.11
2008-02-19 00:00:00-05:00    0.11
2008-05-13 00:00:00-04:00    0.11
2008-08-19 00:00:00-04:00    0.11
2008-11-18 00:00:00-05:00    0.13
2009-02-17 00:00:00-05:00    0.13
2009-05-19 00:00:00-04:00    0.13
2009-08-18 00:00:00-04:00    0.13
2009-11-17 00:00:00-05:00    0.13
2010-02-16 00:00:00-05:00    0.13
2010-05-18 00:00:00-04:00    0.13
2010-08-17 00:00:00-04:00    0.13
2010-11-16 00:00:00-05:00    0.16
2011-02-15 00:00:00-05:00    0.16
2011-05-17 00:00:00-04:00    0.16
2011-08-16 00:00:00-04:00    0.16
2011-11-15 00:00:00-05:00    0.20
2012-02-14 00:00:00-05:00    0.20
2012-05-15 00:00:00-04:00    0.20
2012-08-14 00:00:00-04:00    0.20
2012-11-13 00:00:00-05:00    0.23
2013-02-19 00:00:00-05:00    0.23
2013-05-14 00:00:00-04:00    0.23
2013-08-13 00:00:00-04:00    0.23
2013-11-19 00:00:00-05:00    0.28
2014-02-18 00:00:00-05:00    0.28
2014-05-13 00:00:00-04:00    0.28
2014-08-19 00:00:00-04:00    0.28
2014-11-18 00:00:00-05:00    0.31
2015-02-17 00:00:00-05:00    0.31
2015-05-19 00:00:00-04:00    0.31
2015-08-18 00:00:00-04:00    0.31
2015-11-17 00:00:00-05:00    0.36
2016-02-16 00:00:00-05:00    0.36
2016-05-17 00:00:00-04:00    0.36
2016-08-16 00:00:00-04:00    0.36
2016-11-15 00:00:00-05:00    0.39
2017-02-14 00:00:00-05:00    0.39
2017-05-16 00:00:00-04:00    0.39
2017-08-15 00:00:00-04:00    0.39
2017-11-15 00:00:00-05:00    0.42
2018-02-14 00:00:00-05:00    0.42
2018-05-16 00:00:00-04:00    0.42
2018-08-15 00:00:00-04:00    0.42
2018-11-14 00:00:00-05:00    0.46
2019-02-20 00:00:00-05:00    0.46
2019-05-15 00:00:00-04:00    0.46
2019-08-14 00:00:00-04:00    0.46
2019-11-20 00:00:00-05:00    0.51
2020-02-19 00:00:00-05:00    0.51
2020-05-20 00:00:00-04:00    0.51
2020-08-19 00:00:00-04:00    0.51
2020-11-18 00:00:00-05:00    0.56
2021-02-17 00:00:00-05:00    0.56
2021-05-19 00:00:00-04:00    0.56
2021-08-18 00:00:00-04:00    0.56
2021-11-17 00:00:00-05:00    0.62
2022-02-16 00:00:00-05:00    0.62
2022-05-18 00:00:00-04:00    0.62
2022-08-17 00:00:00-04:00    0.62
2022-11-16 00:00:00-05:00    0.68
2023-02-15 00:00:00-05:00    0.68
2023-05-17 00:00:00-04:00    0.68
2023-08-16 00:00:00-04:00    0.68
2023-11-15 00:00:00-05:00    0.75
2024-02-14 00:00:00-05:00    0.75
Name: Dividends, dtype: float64

In [81]:
msft.history(period="1mo")

,Open,High,Low,...,Volume,Dividends,Stock Splits
Date,,,,,,,
2024-03-04 00:00:00-05:00,413.440002,417.350006,412.320007,...,17596000,0.0,0.0
2024-03-05 00:00:00-05:00,413.959991,414.250000,400.640015,...,26919200,0.0,0.0
2024-03-06 00:00:00-05:00,402.970001,405.160004,398.390015,...,22344100,0.0,0.0
2024-03-07 00:00:00-05:00,406.119995,409.779999,402.239990,...,18718500,0.0,0.0
2024-03-08 00:00:00-05:00,407.959991,410.420013,404.329987,...,17971700,0.0,0.0
2024-03-11 00:00:00-04:00,403.760010,405.679993,401.260010,...,16120800,0.0,0.0
2024-03-12 00:00:00-04:00,407.619995,415.570007,406.790009,...,22457000,0.0,0.0
2024-03-13 00:00:00-04:00,418.100006,418.179993,411.450012,...,17115900,0.0,0.0
2024-03-14 00:00:00-04:00,420.239990,427.820007,417.989990,...,34157300,0.0,0.0
2024-03-15 00:00:00-04:00,419.290009,422.600006,412.790009,...,45049800,0.0,0.0
2024-03-18 00:00:00-04:00,414.250000,420.730011,413.779999,...,20106000,0.0,0.0
2024-03-19 00:00:00-04:00,417.829987,421.670013,415.549988,...,19837900,0.0,0.0
2024-03-20 00:00:00-04:00,422.000000,425.959991,420.660004,...,17860100,0.0,0.0
2024-03-21 00:00:00-04:00,429.829987,430.820007,427.160004,...,21296200,0.0,0.0
2024-03-22 00:00:00-04:00,429.700012,429.859985,426.070007,...,17636500,0.0,0.0
2024-03-25 00:00:00-04:00,425.239990,427.410004,421.609985,...,18060500,0.0,0.0
2024-03-26 00:00:00-04:00,425.609985,425.989990,421.350006,...,16725600,0.0,0.0
2024-03-27 00:00:00-04:00,424.440002,424.450012,419.010010,...,16705000,0.0,0.0
2024-03-28 00:00:00-04:00,420.959991,421.869995,419.119995,...,21871200,0.0,0.0
2024-04-01 00:00:00-04:00,423.950012,427.890015,422.220001,...,16316000,0.0,0.0
2024-04-02 00:00:00-04:00,420.109985,422.380005,417.839996,...,17912000,0.0,0.0
2024-04-03 00:00:00-04:00,419.730011,423.260010,419.089996,...,16475600,0.0,0.0
2024-04-04 00:00:00-04:00,419.730011,427.579987,423.320007,...,2741888,0.0,0.0

You can also download data for multiple tickers at once, like before

In [82]:
data = yf.download("SPY AAPL", start="2017-01-01", end="2017-04-30")
data

[*********************100%%**********************]  2 of 2 completed

Price       Adj Close                  Close  ...        Open     Volume  \
Ticker           AAPL         SPY       AAPL  ...         SPY       AAPL
Date                                          ...
2017-01-03  26.989264  199.200638  29.037500  ...  225.039993  115127600
2017-01-04  26.959057  200.385696  29.004999  ...  225.619995   84472400
2017-01-05  27.096155  200.226471  29.152500  ...  226.270004   88774400
2017-01-06  27.398233  200.942886  29.477501  ...  226.529999  127007600
2017-01-09  27.649185  200.279541  29.747499  ...  226.910004  134247600
2017-01-10  27.677073  200.279541  29.777500  ...  226.479996   97848400
2017-01-11  27.825779  200.845596  29.937500  ...  226.360001  110354400
2017-01-12  27.709599  200.341461  29.812500  ...  226.500000  108344800
2017-01-13  27.660805  200.801346  29.760000  ...  226.729996  104447600
2017-01-17  27.883873  200.093872  30.000000  ...  226.309998  137759200
2017-01-18  27.881550  200.536026  29.997499  ...  226.539993   94852000
2017-01-19  27.832754  199.793182  29.945000  ...  226.839996  102389200
2017-01-20  27.883873  200.527222  30.000000  ...  226.699997  130391600
2017-01-23  27.902464  200.005447  30.020000  ...  226.740005   88200800
2017-01-24  27.876907  201.287781  29.992500  ...  226.399994   92844000
2017-01-25  28.320717  203.030029  30.469999  ...  228.699997  129510400
2017-01-26  28.334661  202.817810  30.485001  ...  229.399994  105350400
2017-01-27  28.336987  202.499435  30.487499  ...  229.419998   82251600
2017-01-30  28.262629  201.243561  30.407499  ...  228.169998  121510000
2017-01-31  28.197565  201.225876  30.337500  ...  226.979996  196804000
2017-02-01  29.917067  201.305481  32.187500  ...  227.529999  447940000
2017-02-02  29.865955  201.438126  32.132500  ...  227.619995  134841600
2017-02-03  29.993752  202.826660  32.270000  ...  228.820007   98029200
2017-02-06  30.274923  202.463989  32.572498  ...  228.869995  107383600
2017-02-07  30.563047  202.472824  32.882500  ...  229.380005  152735200
2017-02-08  30.681547  202.738190  33.009998  ...  228.940002   92016400
2017-02-09  30.903255  203.940948  33.105000  ...  229.240005  113399600
2017-02-10  30.833244  204.745728  33.029999  ...  231.000000   80262000
2017-02-13  31.106287  205.860092  33.322498  ...  232.080002   92141600
2017-02-14  31.510036  206.682587  33.755001  ...  232.559998  132904800
2017-02-15  31.624384  207.761551  33.877499  ...  233.449997  142492400
2017-02-16  31.587055  207.584656  33.837502  ...  234.949997   90338400
2017-02-17  31.673388  207.911880  33.930000  ...  233.949997   88792800
2017-02-21  31.902086  209.150055  34.174999  ...  235.520004   98028800
2017-02-22  31.997780  208.964264  34.277500  ...  236.020004   83347600
2017-02-23  31.862427  209.105835  34.132500  ...  236.880005   83152800
2017-02-24  31.892761  209.371140  34.165001  ...  235.460007   87106400
2017-02-27  31.955772  209.698380  34.232498  ...  236.639999   81029600
2017-02-28  31.969770  209.132294  34.247501  ...  236.669998   93931600
2017-03-01  32.623222  212.059708  34.947498  ...  238.389999  145658400
2017-03-02  32.429520  210.724243  34.740002  ...  239.559998  104844000
2017-03-03  32.620884  210.856918  34.945000  ...  238.169998   84432400
2017-03-06  32.518192  210.228973  34.834999  ...  237.500000   87000000
2017-03-07  32.560211  209.601089  34.880001  ...  237.360001   69785200
2017-03-08  32.438850  209.211960  34.750000  ...  237.339996   74828800
2017-03-09  32.364178  209.477234  34.669998  ...  236.699997   88623600
2017-03-10  32.471527  210.211258  34.785000  ...  237.970001   78451200
2017-03-13  32.485531  210.317398  34.799999  ...  237.619995   69686800
2017-03-14  32.436527  209.512619  34.747501  ...  237.179993   61236400
2017-03-15  32.779583  211.325607  35.115002  ...  237.559998  102767200
2017-03-16  32.833244  210.909943  35.172501  ...  239.110001   76928000
2017-03-17  32.669903  210.539520  34.997501  ...  237.750000  175540000
2017-03-20  33.012959  210.308640  35.365002  ...  237.029999   86168000
2017-03-21  32.634888  207.608398  34.959999  ...  237.470001  158119600
2017-03-22  33.003613  208.096924  35.355000  ...  233.770004  103440800
2017-03-23  32.886929  207.874832  35.230000  ...  234.279999   81385200
2017-03-24  32.821587  207.723801  35.160000  ...  234.380005   89582400
2017-03-27  32.877598  207.510681  35.220001  ...  231.929993   94300400
2017-03-28  33.559044  209.020721  35.950001  ...  233.270004  133499200
2017-03-29  33.633724  209.216095  36.029999  ...  234.990005  116760000
2017-03-30  33.589386  209.882263  35.982498  ...  235.470001   84829200
2017-03-31  33.526375  209.393768  35.915001  ...  235.899994   78646800
2017-04-03  33.535709  209.029587  35.924999  ...  235.800003   79942800
2017-04-04  33.785408  209.162796  36.192501  ...  235.000000   79565600
2017-04-05  33.610378  208.541031  36.005001  ...  236.259995  110871600
2017-04-06  33.526375  209.127289  35.915001  ...  234.940002   84596000
2017-04-07  33.451691  208.914078  35.834999  ...  235.149994   66688800
2017-04-10  33.412022  209.038406  35.792500  ...  235.360001   75733600
2017-04-11  33.052631  208.789764  35.407501  ...  234.899994  121517600
2017-04-12  33.092300  207.874832  35.450001  ...  234.740005   81400000
2017-04-13  32.917263  206.524750  35.262501  ...  233.639999   71291600
2017-04-17  33.099300  208.354492  35.457500  ...  233.110001   66328400
2017-04-18  32.952267  207.732712  35.299999  ...  233.720001   58790000
2017-04-19  32.830917  207.350800  35.169998  ...  234.520004   69313600
2017-04-20  33.241653  209.038406  35.610001  ...  234.149994   93278400
2017-04-21  33.201992  208.372284  35.567501  ...  235.250000   69283600
2017-04-24  33.521698  210.663940  35.910000  ...  237.179993   68537200
2017-04-25  33.729389  211.889679  36.132500  ...  237.910004   75486000
2017-04-26  33.531033  211.756454  35.919998  ...  238.509995   80164800
2017-04-27  33.556705  211.934097  35.947498  ...  238.770004   56985200
2017-04-28  33.524040  211.472198  35.912498  ...  238.899994   83441600

Price
Ticker            SPY
Date
2017-01-03   91366500
2017-01-04   78744400
2017-01-05   78379000
2017-01-06   71559900
2017-01-09   46939700
2017-01-10   63771900
2017-01-11   74650000
2017-01-12   72113200
2017-01-13   62717900
2017-01-17   61240800
2017-01-18   54793300
2017-01-19   66608800
2017-01-20  129168600
2017-01-23   75061600
2017-01-24   95555300
2017-01-25   84437700
2017-01-26   59970700
2017-01-27   59711100
2017-01-30   79737300
2017-01-31   75880800
2017-02-01   79117700
2017-02-02   69657600
2017-02-03   80563200
2017-02-06   57790100
2017-02-07   57931200
2017-02-08   51566200
2017-02-09   65955200
2017-02-10   66015900
2017-02-13   55182100
2017-02-14   71109000
2017-02-15   86785800
2017-02-16   84722400
2017-02-17   77204100
2017-02-21   88946100
2017-02-22   62115200
2017-02-23   74615900
2017-02-24   82381600
2017-02-27   56515400
2017-02-28   96961900
2017-03-01  149158200
2017-03-02   70246000
2017-03-03   81974300
2017-03-06   55391500
2017-03-07   65103700
2017-03-08   78168800
2017-03-09   90683900
2017-03-10   81991700
2017-03-13   57256800
2017-03-14   59880800
2017-03-15   96081800
2017-03-16   78344000
2017-03-17   89002100
2017-03-20   52537000
2017-03-21  131809300
2017-03-22   97569200
2017-03-23  100410300
2017-03-24  112504900
2017-03-27   87454500
2017-03-28   93483900
2017-03-29   61950400
2017-03-30   56737900
2017-03-31   73733100
2017-04-03   85546500
2017-04-04   56466200
2017-04-05  108800600
2017-04-06   69135800
2017-04-07   74412300
2017-04-10   67615300
2017-04-11   88045300
2017-04-12   81864400
2017-04-13   92880400
2017-04-17   68405400
2017-04-18   83225800
2017-04-19   68699900
2017-04-20   92572200
2017-04-21  110389800
2017-04-24  119209900
2017-04-25   76698300
2017-04-26   84702500
2017-04-27   57410300
2017-04-28   63532800

[81 rows x 12 columns]

In [83]:
msft = yf.Ticker("MSFT")
msft.balance_sheet

,2023-06-30,2022-06-30,2021-06-30,2020-06-30
Ordinary Shares Number,7432000000.0,7464000000.0,7519000000.0,7571000000.0
Share Issued,7432000000.0,7464000000.0,7519000000.0,7571000000.0
Net Debt,12533000000.0,35850000000.0,43922000000.0,49751000000.0
Total Debt,59965000000.0,61270000000.0,67775000000.0,70998000000.0
Tangible Book Value,128971000000.0,87720000000.0,84477000000.0,67915000000.0
Invested Capital,253460000000.0,216323000000.0,200134000000.0,181631000000.0
Working Capital,80108000000.0,74602000000.0,95749000000.0,109605000000.0
Net Tangible Assets,128971000000.0,87720000000.0,84477000000.0,67915000000.0
Capital Lease Obligations,12728000000.0,11489000000.0,9629000000.0,7671000000.0
Common Stock Equity,206223000000.0,166542000000.0,141988000000.0,118304000000.0
Total Capitalization,248213000000.0,213574000000.0,192062000000.0,177882000000.0
Total Equity Gross Minority Interest,206223000000.0,166542000000.0,141988000000.0,118304000000.0
Stockholders Equity,206223000000.0,166542000000.0,141988000000.0,118304000000.0
Gains Losses Not Affecting Retained Earnings,-6343000000.0,-4678000000.0,1822000000.0,3186000000.0
Other Equity Adjustments,-6343000000.0,-4678000000.0,1822000000.0,3186000000.0
Retained Earnings,118848000000.0,84281000000.0,57055000000.0,34566000000.0
Capital Stock,93718000000.0,86939000000.0,83111000000.0,80552000000.0
Common Stock,93718000000.0,86939000000.0,83111000000.0,80552000000.0
Total Liabilities Net Minority Interest,205753000000.0,198298000000.0,191791000000.0,183007000000.0
Total Non Current Liabilities Net Minority Interest,101604000000.0,103216000000.0,103134000000.0,110697000000.0
Other Non Current Liabilities,17981000000.0,15526000000.0,13427000000.0,10632000000.0
Tradeand Other Payables Non Current,25560000000.0,26069000000.0,27190000000.0,29432000000.0
Non Current Deferred Liabilities,3345000000.0,3100000000.0,2814000000.0,3384000000.0
Non Current Deferred Revenue,2912000000.0,2870000000.0,2616000000.0,3180000000.0
Non Current Deferred Taxes Liabilities,433000000.0,230000000.0,198000000.0,204000000.0
Long Term Debt And Capital Lease Obligation,54718000000.0,58521000000.0,59703000000.0,67249000000.0
Long Term Capital Lease Obligation,12728000000.0,11489000000.0,9629000000.0,7671000000.0
Long Term Debt,41990000000.0,47032000000.0,50074000000.0,59578000000.0
Current Liabilities,104149000000.0,95082000000.0,88657000000.0,72310000000.0
Other Current Liabilities,14745000000.0,13067000000.0,11666000000.0,10027000000.0
Current Deferred Liabilities,50901000000.0,45538000000.0,41525000000.0,36000000000.0
Current Deferred Revenue,50901000000.0,45538000000.0,41525000000.0,36000000000.0
Current Debt And Capital Lease Obligation,5247000000.0,2749000000.0,8072000000.0,3749000000.0
Current Debt,5247000000.0,2749000000.0,8072000000.0,3749000000.0
Pensionand Other Post Retirement Benefit Plans Current,11009000000.0,10661000000.0,10057000000.0,7874000000.0
Payables And Accrued Expenses,22247000000.0,23067000000.0,17337000000.0,14660000000.0
Payables,22247000000.0,23067000000.0,17337000000.0,14660000000.0
Total Tax Payable,4152000000.0,4067000000.0,2174000000.0,2130000000.0
Income Tax Payable,4152000000.0,4067000000.0,2174000000.0,2130000000.0
Accounts Payable,18095000000.0,19000000000.0,15163000000.0,12530000000.0
Total Assets,411976000000.0,364840000000.0,333779000000.0,301311000000.0
Total Non Current Assets,227719000000.0,195156000000.0,149373000000.0,119396000000.0
Other Non Current Assets,30601000000.0,21897000000.0,15075000000.0,13138000000.0
Investments And Advances,9879000000.0,6891000000.0,5984000000.0,2965000000.0
Long Term Equity Investment,9879000000.0,6891000000.0,5984000000.0,2965000000.0
Goodwill And Other Intangible Assets,77252000000.0,78822000000.0,57511000000.0,50389000000.0
Other Intangible Assets,9366000000.0,11298000000.0,7800000000.0,7038000000.0
Goodwill,67886000000.0,67524000000.0,49711000000.0,43351000000.0
Net PPE,109987000000.0,87546000000.0,70803000000.0,52904000000.0
Accumulated Depreciation,-68251000000.0,-59660000000.0,-51351000000.0,-43197000000.0
Gross PPE,178238000000.0,147206000000.0,122154000000.0,96101000000.0
Leases,8537000000.0,7819000000.0,6884000000.0,5487000000.0
Other Properties,14346000000.0,13148000000.0,11088000000.0,8753000000.0
Machinery Furniture Equipment,81207000000.0,66491000000.0,56594000000.0,46043000000.0
Buildings And Improvements,68465000000.0,55014000000.0,43928000000.0,33995000000.0
Land And Improvements,5683000000.0,4734000000.0,3660000000.0,1823000000.0
Properties,0.0,0.0,0.0,0.0
Current Assets,184257000000.0,169684000000.0,184406000000.0,181915000000.0
Other Current Assets,21807000000.0,16924000000.0,13393000000.0,11482000000.0
Hedging Assets Current,6000000.0,8000000.0,78000000.0,0.0
Inventory,2500000000.0,3742000000.0,2636000000.0,1895000000.0
Finished Goods,1768000000.0,2516000000.0,1367000000.0,1112000000.0
Work In Process,23000000.0,82000000.0,79000000.0,83000000.0
Raw Materials,709000000.0,1144000000.0,1190000000.0,700000000.0
Receivables,48688000000.0,44261000000.0,38043000000.0,32011000000.0
Accounts Receivable,48688000000.0,44261000000.0,38043000000.0,32011000000.0
Allowance For Doubtful Accounts Receivable,-650000000.0,-633000000.0,-751000000.0,-788000000.0
Gross Accounts Receivable,49338000000.0,44894000000.0,38794000000.0,32799000000.0
Cash Cash Equivalents And Short Term Investments,111256000000.0,104749000000.0,130256000000.0,136527000000.0
Other Short Term Investments,76552000000.0,90818000000.0,116032000000.0,122951000000.0
Cash And Cash Equivalents,34704000000.0,13931000000.0,14224000000.0,13576000000.0
Cash Equivalents,26226000000.0,5673000000.0,6952000000.0,7666000000.0
Cash Financial,8478000000.0,8258000000.0,7272000000.0,5910000000.0

### YAHOOFINANCIALS

In [ ]:
from yahoofinancials import YahooFinancials
tech_stocks = ['AAPL']

In [ ]:
yahoo_financials_tech = YahooFinancials('tech_stocks')
yahoo_financials_tech

In [ ]:
tech_cash_flow_data_an = yahoo_financials_tech.get_financial_stmts('annual', 'balance')

In [ ]:
tech_cash_flow_data_an

In [7]:
yahoo_financials_tech.get_net_income()

TypeError: unsupported operand type(s) for -: 'datetime.datetime' and 'str'

In [8]:
tech_cash_flow_data_an

NameError: name 'tech_cash_flow_data_an' is not defined

### WORLD BANK

In [12]:
import pandas as pd
import world_bank_data as wb
pd.set_option('display.max_rows', 100)

ModuleNotFoundError: No module named 'world_bank_data'

In [ ]:
wb.get_topics()

In [ ]:
wb.get_sources()

In [ ]:
wb.get_countries()

In [ ]:
box = wb.get_indicators(topic=3, source=25)

In [ ]:
box

In [ ]:
wb.get_series('NY.GDP.MKTP.KD.ZG', mrv=1)

In [ ]:
wb.get_series('SP.POP.TOTL', mrv=1)

In [ ]:
import wbdata

In [ ]:
data = wbdata.get_data('SP.POP.TOTL', country = 'SWE' )

In [ ]:
data

In [ ]:
countries = 'SWE'                                                                                             

indicators = {"IC.BUS.EASE.XQ": "doing_business", "NY.GDP.PCAP.PP.KD": "gdppc"}         

df = wbdata.get_dataframe(indicators, country=countries, convert_date=True)   

df.describe() 
df

In [ ]:
import wbdata
import pandas
import matplotlib.pyplot as plt
 
#set up the countries I want
countries = ["CL","UY","HU"]
 
#set up the indicator I want (just build up the dict if you want more than one)
indicators = {'NY.GNP.PCAP.CD':'GNI per Capita'}
 
#grab indicators above for countires above and load into data frame
df = wbdata.get_dataframe(indicators, country=countries, convert_date=False)

#df is "pivoted", pandas' unstack fucntion helps reshape it into something plottable
dfu = df.unstack(level=0)

# a simple matplotlib plot with legend, labels and a title
dfu.plot(); 
plt.legend(loc='best'); 
plt.title("GNI Per Capita ($USD, Atlas Method)"); 
plt.xlabel('Date'); plt.ylabel('GNI Per Capita ($USD, Atlas Method')

### EUROSTAT

In [13]:
import eurostat
toc = eurostat.get_toc()
toc[0]

ModuleNotFoundError: No module named 'eurostat'

In [ ]:
toc[2]

In [ ]:
import eurostat
toc_df = eurostat.get_toc_df()
toc_df

In [ ]:
toc_df.iloc[:50]

In [ ]:
box = eurostat.get_data('MED_PS43')

In [ ]:
par_values = eurostat.get_par_values('GOV_10DD_SLGD', 'geo')
par_values

In [ ]:
pars = eurostat.get_pars('GOV_10DD_SLGD')
pars

In [ ]:
data = eurostat.get_data_df('GOV_10DD_SLGD', filter_pars={ 'geo': ['AT','BE' ]})
data